### ISSUE TITLE
Crash under iPhone OS 4.0

### ISSUE THREAD

**Issue by andresendo** [bitstadium/QuincyKit#1]
Hello,
i try to add the CrashReporter under iPhone OS 4.0 and its crashed with with: 

2010-04-28 08:15:47.980 AppName[5247:307] +[NSTimer mainBundle]: unrecognized selector sent to class 0x3e1e1d54
2010-04-28 08:15:48.065 AppName[5247:307] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSTimer mainBundle]: unrecognized selector sent to class 0x3e1e1d54'

If i remove the "CrashReportSender sharedCrashReportSender" part, my App works without Problemes.

Any idea for that?

Thanks!

**Comment by DerAndereAndi** [comment]
Hi,

I ran the CrashReporterDemo app with SDK 4.0 in the simulator, got no problems at all. Maybe you could do the same and then check the differences in your project.

Just looking at the text you send I have no idea what is wrong.

Check the framework is added, check the CrashReportSender files are added and included, check the invokation method is done correctly as in the demo app.
- Andreas

**Comment by fabiankr** [comment]
I can't get the project compiled with the 4.0 GM SDK. It seems that Xcode can't find the framework, though header search paths are correct.

**Comment by DerAndereAndi** [comment]
Ich hab am Montag Abend ne neue Version gemacht, schau einfach an diesem WE mal ob du mich erreichst. Dann geb ich dir das Teil. Muss noch was testen und einbauen fuer ein neues Release.

**Comment by DerAndereAndi** [comment]
Check out latest iPhone client code which supports all iOS versions and also armv7 symbolication
