### ISSUE TITLE
Crash on Device before launching : line crashReporter enableCrashReporterAndReturnError

### ISSUE THREAD

**Issue by amitbattan** [bitstadium/QuincyKit#103]
Hi I am trying to integrate quincykit in a test application 
App runs on simulator but crash on ipad before launching in BWQuincyManager

Crash on line

```
      // Enable the Crash Reporter
      if (![crashReporter enableCrashReporterAndReturnError: &error])
        NSLog(@"WARNING: Could not enable crash reporter: %@", error);
```

Even Demo code also getting crash.

**Comment by DerAndereAndi** [comment]
The code runs fine for me and lots of others. Haven't heard of such an issue. Could you give us more details. Like the actual crash report, Xcode version you are using, compiling demo project without any changes and it crashes?
