### ISSUE TITLE
Gestalt is deprecated on 10.8

### ISSUE THREAD

**Issue by ghost** [bitstadium/QuincyKit#106]
BWQuincyManager is using Gestalt on OS X to get the current system version. This call is deprecated on 10.8. Please change.

**Comment by DerAndereAndi** [comment]
Thanks, we'll take it up in the new PLCrashReporter build which is soon to be released. There the same checks are done and this SDK is using the info from PLCrashReporter directly.

**Comment by DerAndereAndi** [comment]
It seems like there is currently no replacement available. See also this discussion on stackoverflow: http://stackoverflow.com/questions/11072804/mac-os-x-replacement-for-gestalt-for-testing-os-version-at-runtime

I filed a bug report: rdar://11798430

**Comment by DerAndereAndi** [comment]
The new version uses PLCrashReporter which also solves this problem.
