### ISSUE TITLE
Upgrading?

### ISSUE THREAD

**Issue by sdarlington** [bitstadium/QuincyKit#107]
More a question than an issue...

I have not updated either the server or client code since I first integrated it over a year ago. It looks as though there have been substantial changes since then.

Is it "safe" to upgrade the server independently of the client? Will old versions of the client continue to work or should I switch to a different end-point? Any other gotchas that I should be aware of? Or is this unanswerable without knowing the exact versions?

Thanks.

**Comment by DerAndereAndi** [comment]
As far as I remember the changes, all are backwards compatible to older clients versions. So it is "safe" from my perspective.

**Comment by sdarlington** [comment]
Good to know, thanks for your super-swift response.
