### ISSUE TITLE
Feature Request: detect jailbroken devices

### ISSUE THREAD

**Issue by futuretap** [bitstadium/QuincyKit#11]
A simple grep for "MobileSubstrate" could do the job. Would be convenient to narrow down issues. A "jb" suffix could be appended to the os string. That way it would be immediately obvious in in the System OS Overview if a crash only happens on jailbroken devices.

**Comment by DerAndereAndi** [comment]
Good idea. Will take it up.

**Comment by foozmeat** [comment]
I believe this has been added.

**Comment by DerAndereAndi** [comment]
Good point, it actually has been added :)
