### ISSUE TITLE
Correct sorting of version numbers in the form x.y.z

### ISSUE THREAD

**Issue by ahndee** [bitstadium/QuincyKit#111]
Changing lines 225 & 227 in admin/app_versions.php from

```
[…] ORDER BY […] version desc, […]
```

to

```
[…] ORDER BY […] INET_ATON(SUBSTRING_INDEX(CONCAT(version, '.0.0.0'),  '.', 4)) desc, […]
```

Will correctly sort version numbers in the form x.y.z (e.g., sort as 1.9, 1.10, 1.11 rather than 1.10, 1.11, 1.9)

**Comment by DerAndereAndi** [comment]
Thanks. I just added this to the develop branch.
