### ISSUE TITLE
Security issue on crash_v200.php?

### ISSUE THREAD

**Issue by Leechael** [bitstadium/QuincyKit#112]
https://github.com/TheRealKerni/QuincyKit/blob/develop/server/crash_v200.php#L288

than

https://github.com/TheRealKerni/QuincyKit/blob/develop/server/crash_v200.php#L604

`platform` has not been escaped. May be that's a security issue... SQL Injection?

**Comment by DerAndereAndi** [comment]
This is now fixed.
