### ISSUE TITLE
Crashlogs on server side sometimes lack binary images UUID

### ISSUE THREAD

**Issue by biappi** [bitstadium/QuincyKit#119]
Recently I've switched from an in-house crash reporting solution to QuincyKit.

After we've deployed the application, in every crash report we get on the server side, the binary UUID of at least one (but usually much, much more) loaded images gets stripped out.

I don't think this is an issue of PLCrashReporter, since it's the we've been using that our in-house solution, and we never seen this issue.

Of course, not having the binary images UUIDs prevents the system, or us for that matter, to desymbolicate the crashlog.

I didn't have time to debug the issue, so i don't know if the crash file gets corrupted on the device or on the server. Also it seems the this issue is not reported on the tracker here on GitHub.

Is this a known issue? There are any solutions?

**Comment by DerAndereAndi** [comment]
There is no known issue on that part and it is working perfectly fine with hundrets of thousands of crash reports. Without further debugging and information it is impossible to say what is going wrong on your side.

**Comment by biappi** [comment]
Based on your experience, there's any area of the project that's directly related to this issue you can advise to look into? Or is just general blackness here?

**Comment by DerAndereAndi** [comment]
You should try using the latest QuincyKit code and PLCrashReporter framework from this repository. I guess you are using older versions of both or a PLCrashReporter build that is not from this repository. Just wild guesses though.

**Comment by biappi** [comment]
Sorry for the seemingly dumb question, but I want to be sure =).

By latest you mean HEAD or some released/tagged version?

**Comment by DerAndereAndi** [comment]
Latest released version is identical to the latest development head.
