### ISSUE TITLE
Updated to HEAD

### ISSUE THREAD

**Issue by steipete** [bitstadium/QuincyKit#12]
... but now it catches crashes but displays "No data found" ?

I also updated the client code...

**Comment by DerAndereAndi** [comment]
Sorry, I don't get it. Could you be a little more specific of what happens where?

**Comment by steipete** [comment]
here are some screenshots

https://skitch.com/steipetee/rrkkx/crashreporter-admin-interface-crash-patterns

https://skitch.com/steipetee/rrkkw/crashreporter-admin-interface-list

**Comment by steipete** [comment]
So, I'm getting crash reports, but they are somehow not saved in the database.

**Comment by DerAndereAndi** [comment]
It seems you did not upgrade the crash table to contain the new device type field. Check the SQL file fir the required changes

**Comment by steipete** [comment]
ahh; that could be. thanks. i'll try out in a sec

maybe there should be a warning if the shema is not the current one; guess i won't be the only one with that problem...

**Comment by steipete** [comment]
rebuilt database, works now, thanks!

**Comment by DerAndereAndi** [comment]
A better way would be to have an installer/update script that does it all. But I have currently no time do that. Everybody is welcome to join in and help out :)
