### ISSUE TITLE
What about SQLite-Support?

### ISSUE THREAD

**Issue by sticksen** [bitstadium/QuincyKit#120]
Hey,
is it planned to support SQLite (or other DBs) at some time in the future? Or is there any problem with SQLite and the data QuincyKit uses?

Cheers,
Marc

**Comment by DerAndereAndi** [comment]
Hi Marc,

I don't have any plans on implementing support for other databases, I just don't have the time and personal need. But pull-requests are always welcome :)

In general it has to be considered that all crash reports are stored into one table which can get very large if people don't delete older reports from it. I have seen installations reaching the 2GB table limit in MySQL pretty soon and the system getting pretty slow in that case.

The server was developed to get it work quickly, there wasn't much done on implementing a nice code design or anything like that.

Best,
Andreas
