### ISSUE TITLE
The QuincyKit Demo project can't trigger crash

### ISSUE THREAD

**Issue by alexlucky** [bitstadium/QuincyKit#124]
Hi,I am setting up QuincyKit demo project which can trigger crash. I have set up PHP and mysql on server and the test_setup.php shows everything is fine. I followed the instructions on quincykit but ran into problems. The master branch demo project can build successfully on Xcode and i can trigger a crash with it. But seems the crash can't be submitted.Because After I triggered the crash and restart the app, there is NO alert window asking me to send crash report. 
I suspect maybe the debugger of Xcode interceptted the crash. But after i close my Xcode and try it again only in simulator, I still can't see the crash reporting alert window.

**Comment by DerAndereAndi** [comment]
You need to make sure, that when the crash happens:
1. the SDK is initialized
2. now other SDK is grabbing the exception instead
3. Xcode debugger is not connected.

Best,
Andreas

**Comment by alexlucky** [comment]
Hi,Andreas. Thank you so much for the quick reply.
I can set the debugger to none via Xcode product->Edit scheme->debugger. But the SDK part confuses me. Is there any way i can make sure the SDK part?
Thank you for your time.

**Comment by DerAndereAndi** [comment]
Here is how to do this:
1. Deploy the app to the simulator/device, e.g. choose "Run" in Xcode. once it started on the device, choose "Stop" in Xcode.
2. Start the app ON the simulator/device
3. Let the app crash
4. a) Start the app again, alert should show app
4. b) Start the app with Xcode debugger attached (e.g. via "Run" in Xcode) and check your code does the right thing

**Comment by alexlucky** [comment]
Thanks for the instructions. But i think that's what i have been doing these days. I also set the right submission URL. Still no luck to see the crash reporting alert window:)
Any other thoughts? Thanks a lot.

**Comment by DerAndereAndi** [comment]
Make sure that the SDK setup code really gets executed on startup and that there is no other SDK setup that catches your crashes/exceptions instead.

**Comment by alexlucky** [comment]
Is there any change needed in the code except the submissionURL?

**Comment by DerAndereAndi** [comment]
No. You should check the demo app in the repository and then compare it with your own apps setup. Everything else is now just wild guessing what you might possibly be doing or not doing correctly.

**Comment by alexlucky** [comment]
I believe I have done everything in the setup instruction.
when accessing crash_v200.php on my web server I get the code -3, does that mean anything?

**Comment by DerAndereAndi** [comment]
If you don't see the dialog showing up on the next start, and don't have set it to autosend crash reports, it will never contact your server. You really should test and debug to exactly know what is going on. This is right now walking in the dark for me. Also check the server code for the response codes.

Please debug yourself and come back once you have exact data what is happening when and where a problem is, than me or others can help.

**Comment by alexlucky** [comment]
Hi,Andreas,
I finally can see the alert window after trigger a crash. Because i switch another directory to place the project.
But after i send crash report, my server and database can't receive the crashes. From what i see in the log,
 File does not exist: /var/www/html/crash_v200.phpapi
I think this strange php name is due to the following code:
request = [NSMutableURLRequest requestWithURL:
               [NSURL URLWithString:[NSString stringWithFormat:@"%@api/2/apps/%@/crashes?sdk=%@&sdk_version=%@",
                                     self.submissionURL,
                                     [self.appIdentifier stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding],
                                     SDK_NAME,
                                     SDK_VERSION
                                     ]
                ]];
Is there anything wrong with the combination of the request URL?

**Comment by alexlucky** [comment]
I changed the URL combination in the source code, adding a '/' before api. But still can't get crash in database.
And i also set acceptallapps to true.
I can see the access log from server, so i think the connection is fine.
