### ISSUE TITLE
Sending symbolicated data back to the server ... Warning: fsockopen()

### ISSUE THREAD

**Issue by lukaszmargielewski** [bitstadium/QuincyKit#127]
I am getting warning when symbolicated crash is being back to the server:
Why script is having problem with uploading data when downloading is successful?

Processing crash id 194 ...
  Downloading crash data ...
  Writing log data into temporary file ...
  Symbolicating ...
  Sending symbolicated data back to the server ...

Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/lukas/Xcode_projects/iPhone/QuincyKitDesymbolication/symbolicate.php on line 48
Warning: fsockopen(): unable to connect to <MYDOMAIN>/iphone/crashreports:80 (php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known) in /Users/lukas/Xcode_projects/iPhone/QuincyKitDesymbolication/symbolicate.php on line 48
  Deleting temporary files ...

**Comment by demonnico** [comment]
hey,man
maybe u'd check serverconfig.php, and as far as i know:
$hostname must be a pure host name, can't contain any subdirectory.
good luck.
