### ISSUE TITLE
Is it possible to perform symbolication this way?

### ISSUE THREAD

**Issue by alexlucky** [bitstadium/QuincyKit#128]
Hi, I have set up a linux machine as web server. I know the symbolcation has to be performed on Mac platform.But is it possible to have a symbolicate button after every crash that can remotely run symbolicate script and send back symbolicated file to web server if we had put app and dsym files on Mac? Because currently, to perform the remote symbolicate function, I generally run "php symbolicate.php" or "symbolicate.sh", but it seems would traverse all the crashes in to-do list whose "done" column in databse is 0. Sometimes we may need to symbolicate only one crash, which will be flexiable if we do this on web. And i notice that if the "done" column in symbolicated table is 2, there will be a "symbolicate" button after the crash. But i am not sure the button action.

And another issue is the "delete" button, i think it's risky if the delete button is enabled for all users in a product line. Do you think it's necessary to add some user management to distribute different priviliges?

And another thing i want to talk about is, should the original crash file be shown if we click "symbolicate again" button?
Thank you for your time.

**Comment by DerAndereAndi** [comment]
Hi,
1. Invoke symbolication via a button on the website on your Mac
   This would require the following things:
   - A kind of web server running on your Mac
   - This web server being reachable from the server running the QuincyKit Backend, e.g. by opening a port in the router
   - Code on your Macs web server to process the symbolication for a specific crash
     This is surely all doable, but nothing I will develop. You are free to fork the project for that and provide a patch. But it is much much easier just to setup the current script as a cron job to frequently check the webserver for crash reports that should be symbolicated and process them. See https://github.com/TheRealKerni/QuincyKit/wiki/Remote-symbolication
2. Delete button and user management
    This is nothing I am planning to develop. As above, you are free to fork and do it yourself. I intended this to be as easy as possible and am working myself rather on the HockeyApp.net web service which offers this and many more pro features. This open source project, since it was mostly developed by myself, does not have the scope to go beyond the current functionality.
3. Symbolicate again
   This will add the crash to the symbolication queue again. If symbolication for whatever reason did not work on your Mac, then the crash report is not changed and it shows as it was. The system does only save one "version" of each crash report, it is not intended to have an option to show the incoming crash report (wouldn't make sense to have that anyway).

Andreas
