### ISSUE TITLE
Is it possible to catch jettisoned crashes?

### ISSUE THREAD

**Issue by duke4e** [bitstadium/QuincyKit#129]
Hi, I've setted up QuincyKit and both iOS part and PHP part are working as they should.  BUT, if the app crashes after memory warning, that kind of crash isn't reported to my server. This kind of error is also logged in XCode as "unknown" app. So, my question is - can this kind of crash be sent to server (and I'm doing something wrong), or are this jettisoned crashes unavailable to be obtained by my app?

Thank you for your time.

**Comment by DerAndereAndi** [comment]
This page shows what can be detected and what can't: http://support.hockeyapp.net/kb/how-tos-faq/which-types-of-crashes-can-be-collected-on-ios-and-os-x

**Comment by duke4e** [comment]
Thank you.
