### ISSUE TITLE
Grouping & feedback not working

### ISSUE THREAD

**Issue by TheSpring** [bitstadium/QuincyKit#133]
I understand that since iOS4 and more in iOS 5 , each crash is mostly unique because that each app starts on different memory address and grouping works only after symbolication , therefore feedback will not work any more 

Is there any idea to solve this (maybe a new php script on server to detect grouping in a different way) or it's a lost issue so better to give it up ? 

Thanks for help !

**Comment by DerAndereAndi** [comment]
The grouping now works again with the new code in develop branch. The feedback feature has been removed though.
