### ISSUE TITLE
chmod +x symbolicatecrash.pl do nothing

### ISSUE THREAD

**Issue by Piero87** [bitstadium/QuincyKit#134]
Hello, i have followed the wiki step by step, now i'm trying to install the Setup Local Symbolification on my Mac, this is what i have do:

1.copy all content of local folder in my folder in the Document;
2. i adjust the serverconfig.php
3.Make the modified symbolicatecrash.pl file from the /server/local/ directory executable: so i do this: `chmod +x symbolicatecrash.pl` i press enter and nothing happen, return the terminal line, so then i tried to do `symbolicatecrash MyApp/mycrash.crash` and the terminal tell me this: `-bash: symbolicatecrash: command not found`, i can't understand why.
If instead i do this: `./symbolicatecrash MyApp/mycrash.crash` works...

**Comment by DerAndereAndi** [comment]
1. `chmod +x symbolicatecrash.pl` sets the executable flag for the file. If you would do a `ls -l` before and after, you would see what happened.
2. The command does not execute the script. You may want to check the documentation for `chmod`, e.g. `man chmod`
3. To execute the script from the current path use: `./symbolicatecrash.pl`

**Comment by Piero87** [comment]
thank you very much, i can't also understand what i have to write in the `com.crashreportsender.symbolicator.plist` and the `symbolycate.sh` file, the guide tell this:

Adjust the paths to the directory the files are located in `symbolicate.sh` (don’t forget chmod +x) and `com.crashreportsender.symbolicator.plist`

in the symbolicate file i see this: `#cd <the directory the files are located>`, what i have to write? the absolute path from the root? or the path from the `symbolicate.s`h folder? and in the `/local/` i have do this:

`-MyApps
---FirstApp/FirstApp_1_5/then here .app and .app.dSYM
---SecondoApp/SecondApp_1_0/then here .app and .app.dSYM`

what folder i have to write, and how? the same for the plist file, what i have to write and where?

thank you
