### ISSUE TITLE
Quincy Kit - arm64 support for iPhone 5S

### ISSUE THREAD

**Issue by sinusekhar** [bitstadium/QuincyKit#137]
Can you please share your roadmap on adding support for 64 Bit iPhone architecture for 5S? The current version of Quincy Kit doesn't work when targeted against arm64.

Regards,
Sinu

**Comment by duke4e** [comment]
AFAIK, 64 bit support is still in beta. You can get 64 bit crash reporter here (https://www.plcrashreporter.org/download), and then just merge it with Quincy kit.

**Comment by DerAndereAndi** [comment]
Hi,

here are some points:
1. PLCrashReporter 64 bit support is not finished yet.
2. The new PLCrashReporter requires adjustments to multiple parts in QuincyKit, so this is not a simple replacement of its binary.
3. I will take a look at QuincyKit once I find the time to do so. If you are using HockeyApp as a backend, I highly recommend to switch to HockeySDK-iOS instead which will get support earlier than QuincyKit.

Best,
Andreas

**Comment by sinusekhar** [comment]
Thanks so much for the details duke4e and Andreas.

We are not using HockeyApp as a backend, but our own. 
Looking forward to the QuincyKit release with arm64 support.

In the mean time we will also take a look to see what is involved and if we end up adding this support to QuincyKit sooner, we will share it with you.

Thanks for making this SDK available to the community.

**Comment by duke4e** [comment]
Here's a experimental support for arm64. Since I don't have access to new iPhone, I have no ways of testing this.

www.meritumapps.com/apps/QuincyKit-develop.zip

If everything works well, feel free to include it in QuincyKit :)

**Comment by DerAndereAndi** [comment]
Hi,

thanks. Without testing and just looking over the code I can see multiple things that are wrong or not good. In addition PLCR is still not finished, so I suggest you'll wait until I have some time.

On another note: I do not recommend to anyone to ship 64 bit versions of their apps without testing your app on a 64 bit device yourself. You can get yourself into trouble very easily!
- Andreas

**Comment by sinusekhar** [comment]
Thanks so much for providing a beta release.

**Comment by mapedd** [comment]
How the status of 64bit support for PLCrashReporter look like? Any predictions when it can be ready?

**Comment by landonf** [comment]
PLCrashReporter has a 1.2 release candidate with full ARM64 support; refer to https://www.plcrashreporter.org/download and https://www.plcrashreporter.org/download/changelog for more details.

**Comment by DerAndereAndi** [comment]
The new commits in the develop branch now contains the latest PLCrashReporter version with 64bit support and many more improvements.

**Comment by sticksen** [comment]
Will there be a new CocoaPod version for the 64Bit release? Always fetching :head seems a little bit 'unsafe' to me.
