### ISSUE TITLE
Undefined variable errors reported by server.

### ISSUE THREAD

**Issue by Whiffer** [bitstadium/QuincyKit#142]
I have installed, configured and now trying to test a new QuincyKit server using latest commit. The following errors are reported in the apache error log when an iOS client is reporting a test crash:

[Fri Mar 07 10:48:40 2014] [error] [client 192.168.3.185] PHP Notice:  Undefined variable: push_activated in /Library/Server/Web/Data/Sites/Default/admin/common.inc on line 502
[Fri Mar 07 10:48:40 2014] [error] [client 192.168.3.185] PHP Notice:  Undefined variable: boxcar_activated in /Library/Server/Web/Data/Sites/Default/admin/common.inc on line 512
[Fri Mar 07 10:48:40 2014] [error] [client 192.168.3.185] PHP Notice:  Undefined variable: mail_activated in /Library/Server/Web/Data/Sites/Default/admin/common.inc on line 518
[Fri Mar 07 10:48:40 2014] [error] [client 192.168.3.185] PHP Notice:  Undefined variable: symbolicate in /Library/Server/Web/Data/Sites/Default/admin/common.inc on line 549

The crash report gets added to the database correctly, but the Prowl notification never gets sent.   I've been trying to dig into this, but I'm stuck between Stages 3 & 4 in the "Six Stages of Debugging".

**Comment by testzugang** [comment]
Also email notifications are not sent. The whole notification block seems to be broken.
