### ISSUE TITLE
common.inc (491) my_sql_free_result() called on non resource queries

### ISSUE THREAD

**Issue by xhruso00** [bitstadium/QuincyKit#143]
my_sql_free_result() called on non resource queries. Can be used only on resources otherwise it emits warning

For SELECT, SHOW, DESCRIBE, EXPLAIN and other statements returning resultset, mysql_query() returns a resource on success, or FALSE on error.

For other type of SQL statements, INSERT, UPDATE, DELETE, DROP, etc, mysql_query() returns TRUE on success or FALSE on error.

**Comment by DerAndereAndi** [comment]
I'd appreciate a pull request.

**Comment by karlvr** [comment]
I have corrected this, and several other server issues in my fork at https://github.com/karlvr/QuincyKit

I'd love to PR various things back, but it looks like this project isn't alive any more, so perhaps grab from my fork if you're still using this!
