### ISSUE TITLE
Incorrect setter implementation in BWQuincyManager causing crashes

### ISSUE THREAD

**Issue by xhruso00** [bitstadium/QuincyKit#144]
1. Memory management is non ARC => own implementation should correctly retain of setters should correctly retain values. The same applies when loading them from disk (property files).
2. Use copy instead of retain in case of NSString.

Example:
- (void)setUserID:(NSString *)userID {
  id oldUserId = _userID;
  _userID = [userID copy];
  [oldUserId release];
  [self saveSettings];
  }
- (void)setUserName:(NSString *)userName {
  id oldUserName = _userName;
  _userName = [userName copy];
  [oldUserName release];
  [self saveSettings];
  }
- (void)setUserEmail:(NSString *)userEmail {
  id oldUserEmail = _userEmail;
  _userEmail = [userEmail copy];
  [oldUserEmail release];
  [self saveSettings];
  }

**Comment by DerAndereAndi** [comment]
Memory management is ARC. Check the development branch.

**Comment by xhruso00** [comment]
Mac is still non-ARC. iOS is ARC

**Comment by DerAndereAndi** [comment]
Right. Thanks for clarifying the context. A pull request for the fix would be appreciated.
