### ISSUE TITLE
EXC_BAD_ACCESS during hasPendingCrashReport while checking if _crashesDir exists

### ISSUE THREAD

**Issue by pkester** [bitstadium/QuincyKit#148]
[BWQuincyManager hasPendingCrashReport] is giving EXC_BAD_ACCESS at line 640.

  if ([_fileManager fileExistsAtPath:_crashesDir]) {

If I look inside the debugger, po _crashesDir prints out a memory address instead of the actual NSString.

I added pauses when _crashesDir is set and everything works fine up until it returns self.
Xcode Version 5.1 (5B130a) and  iOS 7.1 on device

**Comment by DerAndereAndi** [comment]
I can not reproduce this here. Did you try with the demo project?

**Comment by pkester** [comment]
I removed all the QuincyKit files and replaced them. I think maybe I did not update the CrashReporter framework as it was in a different spot. It works now.
