### ISSUE TITLE
Quincy not saving crash reports to database

### ISSUE THREAD

**Issue by magin** [bitstadium/QuincyKit#149]
I have setup quincy on the client and the server. On the client I use:

```
[[BWQuincyManager sharedQuincyManager] setSubmissionURL:@"http://site.com/server/crash_v300.php"];
[[BWQuincyManager sharedQuincyManager] startManager];
```

and on the client I use the "test.php" (echoes Passed on all) and crash_v300 (echoes '-3' to verify it's working.

However when the app crashes and there is an alert promting me whether I want to send a crash report and I say 'Yes'. It doesn't saves the crash report in my database. Any ideas?

**Comment by DerAndereAndi** [comment]
Enable debug logging on the SDK via https://github.com/TheRealKerni/QuincyKit/blob/develop/client/iOS/BWQuincyManager.h#L279 and check the output in the console. You can also let the app crash without the debugger attached and then start the app with the debugger to see what is going on.

On the server check that you created an app entry with the bundle identifier or configured it to accept all bundle identifiers: https://github.com/TheRealKerni/QuincyKit/blob/develop/server/config.php.sample#L83

**Comment by KaboomProjeXs** [comment]
Got the same problem...https://github.com/TheRealKerni/QuincyKit/issues/145

**Comment by simonbirdy** [comment]
Had the same problem.
First problem was that for security reasons some PHP actions were blocked by the provider. Had to contact him to remove this protection. 

Second problem was an incorrect mysql query in the common.inc file. 

I had to do a mysql_real_escape_string() for the $crashPatten variable to fix it:

``` php
          // create a new pattern for this bug and set amount of occurrances to 1
            $query = "INSERT INTO ".$dbgrouptable." (bundleidentifier, affected, pattern, location, exception, reason, amount, latesttimestamp) values ('".$bundleidentifier."', '".$version."', '".mysql_real_escape_string($crashPattern)."', '".mysql_real_escape_string($crashLocation)."', '".mysql_real_escape_string($crashException)."', '".mysql_real_escape_string($crashReason)."', 1, ".time().")";
```

To try to find whats you're problem you should implement the delegate functions of BWQuincyManger:
- (void)quincyManager:(BWQuincyManager *)quincyManager didFailWithError:(NSError *)error;

If the returned error code is equal to 510 then it's probably the security restrictions of you're server. If no error is returned it could be the bug in the common.inc file.

I hope this is helpful for you.

**Comment by Zeropointer11** [comment]
Hi i use the QuincyKit version 3.0 and the crashes didn't import in the database i get allways the response : [Quincy] -[BWQuincyManager connectionDidFinishLoading:]/1093 Received API response: <?xml version="1.0" encoding="UTF-8"?><result>0</result>
