### ISSUE TITLE
Quincy kit Client  3.0 for MAC OS is throwing exception

### ISSUE THREAD

**Issue by mritunjayonemail** [bitstadium/QuincyKit#151]
Hi,

I integrated QuincyKit client for MAC OS in my app.After integration when i am trying to execute my app in simulator, i am getting exception:

dyld: Library not loaded: @loader_path/../Frameworks/Quincy.framework/Versions/A/Quincy
  Referenced from: /Users/mkumar5/Library/Developer/Xcode/DerivedData/com.sample.test.mac-ghzcpxyblqilbgdfqhpdxeuhdnvp/Build/Products/Debug/com.sample.test.mac.app/Contents/MacOS/com.sample.test.mac
Reason: image not found

Kindly let me know, what i am missing here? Is Quincy Kit Client 3.0 for MAC OS is production ready?

Regards,
Mritunjay

**Comment by colincameron** [comment]
@mritunjayonemail did you get anywhere with this? I'm experiencing the same error:

```
dyld: Library not loaded: @executable_path/../Frameworks/Quincy.framework/Versions/A/Quincy
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/MyApp-dmngnggepeizqkdfqagrqmohvudl/Build/Products/Debug/My App.app/Contents/MacOS/My App
  Reason: image not found
```

**Comment by mritunjayonemail** [comment]
Please follow the following step, it should solve your problem.
Open the Quincy.xcodeproj
Build the quincy.framework
After that drag the Quincy.framework in your project. To find location of Quincy.framework, right click on Product->Quincy.framework and Show in finder.
In you appDelegate.m add #import <Quincy/BWQuincyManager.h>
In your appDelegate change the invocation of the main window to the following structure
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
  {
  
  [[BWQuincyManager sharedQuincyManager] setSubmissionURL:@"https://crashlog.platform.intuit.com/api/v1/crashes"];
  [[BWQuincyManager sharedQuincyManager] setApiKey:@"akyresYQJQLLRgBIoL119ucHzOfpY89OKNWXGDaR"];
  [[BWQuincyManager sharedQuincyManager] setTrafficType:@"SANDBOX"];
  [[BWQuincyManager sharedQuincyManager] startManager];

}
If you want to to implement any of the delegates, add the following before the startManager call.
    [[BWQuincyManager sharedQuincyManager] setDelegate:self];
     and set the protocol to your appDelegate.
      @interface YourAppDelegate : NSObject <BWQuincyManagerDelegate> {}

   • If you face any issue while running then  You need to add a new Copy Files build phase to your target. Set it to "Frameworks" to copy frameworks and drag a copy of Quincy.framework from your Xcode project into the new Copy Files build phase.
