### ISSUE TITLE
Quincy KIt 3.0 for Mac  sanbox violation?

### ISSUE THREAD

**Issue by mritunjayonemail** [bitstadium/QuincyKit#153]
I integrated my app with Quincy Kit Client 3.0 for Mac. I signed the app and tested for app sandbox violation. After the build I copied my app in Application  folder and generated crash. It is sending the crash properly, but in activity console I am getting below exception, I am not sure whether this is related to sandbox violation?

Jun 11 14:59:07 BANL11914df31.local taskgated-helper[7941]: Starting taskgated-helper
Jun 11 14:59:08 BANL11914df31.local sandboxd[7944]([7941]): taskgated-helper(7941) deny file-read-metadata /private/var/folders
Jun 11 14:59:08 --- last message repeated 1 time ---
Jun 11 14:59:08 BANL11914df31 kernel[0]: Sandbox: sandboxd(7944) deny mach-lookup com.apple.coresymbolicationd
Jun 11 14:59:08 BANL11914df31.local sandboxd[7944]([7941]): taskgated-helper(7941) deny file-read-metadata /private/var/folders
Jun 11 14:59:10 --- last message repeated 18 times ---
Jun 11 14:59:10 BANL11914df31.local taskgated-helper[7941]: Provisioning Profile Validation: profile 'G4SSPX3CBL.com.intuit.crashreport.demoApp' has 10 devices
Jun 11 14:59:11 BANL11914df31 com.apple.launchd.peruser.1784435860[392]([0x0-0xf60f6].com.intuit.crashreport.demoApp[7940]): Exited: Killed: 9
Jun 11 14:59:39 BANL11914df31.local coreaudiod[464]: Disabled automatic stack shots because audio IO is active
Jun 11 14:59:39 BANL11914df31.local coreaudiod[464]: Enabled automatic stack shots because audio IO is inactive

Is this exception has anything to do with app sanbox violation?

**Comment by DerAndereAndi** [comment]
I don't see how/where the SDK is accessing that folder and causing such a sandbox violation.
