### ISSUE TITLE
[QuincyKit 3.0] Crashes would not handle on the server

### ISSUE THREAD

**Issue by Zeropointer11** [bitstadium/QuincyKit#158]
Hi i am using the Version 3.0 and the result from the server was allways:
[Quincy] -[BWQuincyManager connectionDidFinishLoading:]/1093 Received API response: <?xml version="1.0" encoding="UTF-8"?><result>0</result>

the crash is not import to the database and did not show in backend.

the crash looks so:
[Quincy] -[BWQuincyManager sendCrashReports]/930 INFO: Sending crash reports:
<crash><applicationname>QuincyDemo</applicationname><uuids><uuid type="app" arch="armv7">7f36020a61213c5c9011717c35f660b2</uuid></uuids><bundleidentifier>at.test.QuincyDemo</bundleidentifier><systemversion>7.1.2</systemversion><platform>iPhone5,2</platform><senderversion>10</senderversion><version>10</version><uuid>76DC0951-91CA-4CA6-B063-9EA6F1503FB1</uuid><log><![CDATA[Incident Identifier: 76DC0951-91CA-4CA6-B063-9EA6F1503FB1
CrashReporter Key:   9A19995E-5DE4-456A-99A2-DD74D843691E
Hardware Model:      iPhone5,2
Process:         QuincyDemo [740]
Path:            /var/mobile/Applications/A6A58CFC-670A-4C4F-BB6E-6835E5887406/QuincyDemo.app/QuincyDemo
Identifier:      at.test.QuincyDemo
Version:         10
Code Type:       ARM
Parent Process:  launchd [1]

Date/Time:       2014-09-24T09:19:12Z
OS Version:      iPhone OS 7.1.2 (11D257)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x393b71f0
Crashed Thread:  0

Application Specific Information:
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 23 beyond bounds for empty array'

Last Exception Backtrace:
0   CoreFoundation                       0x2e667ecb <redacted> + 130
1   libobjc.A.dylib                      0x38e02ce7 objc_exception_throw + 38
2   CoreFoundation                       0x2e59e2b1 -[__NSArrayI objectAtIndex:] + 176
3   QuincyDemo                           0x000d6d5b 0xd2000 + 19803
4   UIKit                                0x30ece6a7 <redacted> + 90
5   UIKit                                0x30ece643 <redacted> + 38
6   UIKit                                0x30ece613 <redacted> + 46
7   UIKit                                0x30eb9d5b <redacted> + 374
8   UIKit                                0x30ece05b <redacted> + 594
9   UIKit                                0x30ecdd2d <redacted> + 528
10  UIKit                                0x30ec8c87 <redacted> + 758
11  UIKit                                0x30e9de55 <redacted> + 196
12  UIKit                                0x30e9c521 <redacted> + 7120
13  CoreFoundation                       0x2e632faf <redacted> + 14
14  CoreFoundation                       0x2e632477 <redacted> + 206
15  CoreFoundation                       0x2e630c67 <redacted> + 630
16  CoreFoundation                       0x2e59b729 CFRunLoopRunSpecific + 524
17  CoreFoundation                       0x2e59b50b CFRunLoopRunInMode + 106
18  GraphicsServices                     0x3350a6d3 GSEventRunModal + 138
19  UIKit                                0x30efc871 UIApplicationMain + 1136
20  QuincyDemo                           0x000d6935 0xd2000 + 18741
21  QuincyDemo                           0x000d68c8 0xd2000 + 18632

Thread 0 Crashed:
0   libsystem_kernel.dylib               0x393b71f0 __pthread_kill + 8
1   libsystem_c.dylib                    0x39367ff9 abort + 76
2   QuincyDemo                           0x000e7237 0xd2000 + 86583
3   CoreFoundation                       0x2e6681cd <redacted> + 580
4   libobjc.A.dylib                      0x38e02f6b <redacted> + 174
5   libc++abi.dylib                      0x387cd1b3 <redacted> + 78
6   libc++abi.dylib                      0x387ccd17 __cxa_rethrow + 102
7   libobjc.A.dylib                      0x38e02e2f objc_exception_rethrow + 42
8   CoreFoundation                       0x2e59b79f CFRunLoopRunSpecific + 642
9   CoreFoundation                       0x2e59b50b CFRunLoopRunInMode + 106
10  GraphicsServices                     0x3350a6d3 GSEventRunModal + 138
11  UIKit                                0x30efc871 UIApplicationMain + 1136
12  QuincyDemo                           0x000d6935 0xd2000 + 18741
13  QuincyDemo                           0x000d68c8 0xd2000 + 18632

Thread 1:
0   libsystem_kernel.dylib               0x393a4804 kevent64 + 24
1   libdispatch.dylib                    0x392ed2e3 <redacted> + 38

Thread 2:
0   libsystem_kernel.dylib               0x393b7c70 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x3941cadc start_wqthread + 8

Thread 3:
0   libsystem_kernel.dylib               0x393b7c70 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x3941cadc start_wqthread + 8

Thread 4:
0   libsystem_kernel.dylib               0x393a4a50 mach_msg_trap + 20
1   CoreFoundation                       0x2e6325e9 <redacted> + 156
2   CoreFoundation                       0x2e630d09 <redacted> + 792
3   CoreFoundation                       0x2e59b729 CFRunLoopRunSpecific + 524
4   CoreFoundation                       0x2e59b50b CFRunLoopRunInMode + 106
5   Foundation                           0x2efdc241 <redacted> + 320
6   Foundation                           0x2f051a0f <redacted> + 1062
7   libsystem_pthread.dylib              0x3941e959 <redacted> + 140
8   libsystem_pthread.dylib              0x3941e8cb _pthread_start + 102
9   libsystem_pthread.dylib              0x3941cae8 thread_start + 8

Thread 5:
0   libsystem_kernel.dylib               0x393b7c70 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x3941cadc start_wqthread + 8

Thread 6:
0   libsystem_kernel.dylib               0x393b7434 __select + 20
1   libsystem_pthread.dylib              0x3941e959 <redacted> + 140
2   libsystem_pthread.dylib              0x3941e8cb _pthread_start + 102
3   libsystem_pthread.dylib              0x3941cae8 thread_start + 8

Thread 7:
0   libsystem_kernel.dylib               0x393b7c70 __workq_kernreturn + 8
1   libsystem_pthread.dylib              0x3941cadc start_wqthread + 8

Thread 0 crashed with ARM Thread State:
    pc: 0x393b71f0     r7: 0x27d31934     sp: 0x27d31928     r0: 0x00000000 
    r1: 0x00000000     r2: 0x00000000     r3: 0xffffffff     r4: 0x00000006 
    r5: 0x3b31318c     r6: 0x15695720     r8: 0x314e17d2     r9: 0x3b313e30 
   r10: 0x314c5984    r11: 0x00000016     ip: 0x00000148     lr: 0x3941f7b7 
  cpsr: 0x00000010 

Binary Images:
   0xd2000 -    0xfdfff +QuincyDemo armv7  <7f36020a61213c5c9011717c35f660b2> /var/mobile/Applications/A6A58CFC-670A-4C4F-BB6E-6835E5887406/QuincyDemo.app/QuincyDemo
0x2d600000 - 0x2d600fff  Accelerate armv7s  <58ca068138d93e988a34a0c8c34b0b11> /System/Library/Frameworks/Accelerate.framework/Accelerate
0x2d60a000 - 0x2d7d7fff  vImage armv7s  <9923548d8ed23bb1b1020130b5d38dab> /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage
0x2d7d8000 - 0x2d8bafff  libBLAS.dylib armv7s  <48f7680a8fd83251ad8415bb090408c3> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBLAS.dylib
0x2d8bb000 - 0x2db73fff  libLAPACK.dylib armv7s  <2547383dc88d3329827b4d76768915ee> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLAPACK.dylib
0x2db74000 - 0x2dbe2fff  libvDSP.dylib armv7s  <83036da6f5d9308bb5fad06b2d29bac9> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvDSP.dylib
0x2dbe3000 - 0x2dbf5fff  libvMisc.dylib armv7s  <addc52a9647f3269965a750366ebed70> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvMisc.dylib
0x2dbf6000 - 0x2dbf6fff  vecLib armv7s  <4a647b20c3f03490aae530226350a4cd> /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib
0x2dbf7000 - 0x2dc17fff  Accounts armv7s  <7dbe9726167b36a38cf1a73eb313f9ec> /System/Library/Frameworks/Accounts.framework/Accounts
0x2dc19000 - 0x2dc80fff  AddressBook armv7s  <081495c24868358ea3f06e320fba44f4> /System/Library/Frameworks/AddressBook.framework/AddressBook
0x2e20b000 - 0x2e329fff  CFNetwork armv7s  <ed4b37345fca3e02bc3d2bbcac484b16> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x2e32a000 - 0x2e385fff  CoreAudio armv7s  <cf2658996f5c30d394af6ad906d8e0af> /System/Library/Frameworks/CoreAudio.framework/CoreAudio
0x2e39e000 - 0x2e592fff  CoreData armv7s  <a060f165568c31289760beb020e70f2e> /System/Library/Frameworks/CoreData.framework/CoreData
0x2e593000 - 0x2e6d6fff  CoreFoundation armv7s  <83decfd26c653905912f5cdb8743f5d9> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x2e6d7000 - 0x2e7fbfff  CoreGraphics armv7s  <840c99b38b9f3ef497079f300ff15a1b> /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
0x2e7fd000 - 0x2e838fff  libCGFreetype.A.dylib armv7s  <f8e0113922b03325a82471e0ef77d7a1> /System/Library/Frameworks/CoreGraphics.framework/Resources/libCGFreetype.A.dylib
0x2e83a000 - 0x2e844fff  libCMSBuiltin.A.dylib armv7s  <8a3e3045c8b732389f72dd226c1c1e54> /System/Library/Frameworks/CoreGraphics.framework/Resources/libCMSBuiltin.A.dylib
0x2ea29000 - 0x2ea43fff  libRIP.A.dylib armv7s  <68accf992a733f58a04315603459e863> /System/Library/Frameworks/CoreGraphics.framework/Resources/libRIP.A.dylib
0x2ea44000 - 0x2eb1dfff  CoreImage armv7s  <706f78907a5d3146b6d9c0382693a112> /System/Library/Frameworks/CoreImage.framework/CoreImage
0x2eba5000 - 0x2ec20fff  CoreMedia armv7s  <df4f98e752493f7daeb9166940a33dba> /System/Library/Frameworks/CoreMedia.framework/CoreMedia
0x2ecca000 - 0x2ed22fff  CoreTelephony armv7s  <ad42b931d27832fa83ed5019f37a6afa> /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
0x2ed23000 - 0x2edb3fff  CoreText armv7s  <1eb3fd81e1203680a1ad0eecd4273594> /System/Library/Frameworks/CoreText.framework/CoreText
0x2edb4000 - 0x2edc3fff  CoreVideo armv7s  <b1c668f2ae323039b02bb52c4a4172b8> /System/Library/Frameworks/CoreVideo.framework/CoreVideo
0x2ef84000 - 0x2f16efff  Foundation armv7s  <52121842f9863ab49b775758dd05db0b> /System/Library/Frameworks/Foundation.framework/Foundation
0x2f350000 - 0x2f3a6fff  IOKit armv7s  <827281a0bc2e3120bc40be79b7e3026b> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x2f3a7000 - 0x2f5b7fff  ImageIO armv7s  <ec4acdf658dd3dec9d2c325db835d987> /System/Library/Frameworks/ImageIO.framework/ImageIO
0x2f5b8000 - 0x2f804fff  JavaScriptCore armv7s  <12b8c035858737c792488a582909734f> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
0x2f8b5000 - 0x2f8b9fff  MediaAccessibility armv7s  <a44ef28b46f236d5a76b63a08976e1dd> /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
0x2fe6b000 - 0x2fecefff  MobileCoreServices armv7s  <c3ab5b49a79334a0bcc84247b3132de6> /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
0x30916000 - 0x3091efff  OpenGLES armv7s  <df9830a0248d36e5a9fabb2e633e9001> /System/Library/Frameworks/OpenGLES.framework/OpenGLES
0x30920000 - 0x30920fff  libCVMSPluginSupport.dylib armv7s  <6f98aa42a1593958a5455706156e9402> /System/Library/Frameworks/OpenGLES.framework/libCVMSPluginSupport.dylib
0x30925000 - 0x30928fff  libCoreVMClient.dylib armv7s  <38ff1c7f12f83f8bac062e8daf9d4c10> /System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib
0x30929000 - 0x30930fff  libGFXShared.dylib armv7s  <a92cda33404b339da0e84a5fe133e06e> /System/Library/Frameworks/OpenGLES.framework/libGFXShared.dylib
0x30931000 - 0x30971fff  libGLImage.dylib armv7s  <7d912d8e3a453456a6e2d806b59aa448> /System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib
0x30b09000 - 0x30c50fff  QuartzCore armv7s  <d5174e25cef83958adf812e37c93a41e> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x30caa000 - 0x30cecfff  Security armv7s  <1e4881d7baad301d86c74515fea45c36> /System/Library/Frameworks/Security.framework/Security
0x30e3c000 - 0x30e8bfff  SystemConfiguration armv7s  <3d6772f0ad5938558a4bc677965db338> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x30e8e000 - 0x31601fff  UIKit armv7s  <e6756dd481773242b35fa4db5378453b> /System/Library/Frameworks/UIKit.framework/UIKit
0x31602000 - 0x31650fff  VideoToolbox armv7s  <584a3e65bebe3025a2656cbf0c53a7a5> /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox
0x319f8000 - 0x319fcfff  AggregateDictionary armv7s  <b613b360be4f31948901570de6a079d2> /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
0x32058000 - 0x32096fff  AppSupport armv7s  <4f0f918a35d733e9b6f49b785ffbf233> /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
0x321c0000 - 0x321ccfff  AssetsLibraryServices armv7s  <19f6f222ffd83c34b022213e4e427815> /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
0x3221a000 - 0x3223ffff  BackBoardServices armv7s  <1ab89a11a7a834e4a36de79352bd9f6b> /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
0x32248000 - 0x3226cfff  Bom armv7s  <bf26b007d10337299e84e9c498b3378d> /System/Library/PrivateFrameworks/Bom.framework/Bom
0x323ff000 - 0x32404fff  CertUI armv7s  <78cc91d2d6b730ee86ea2a768d666d4a> /System/Library/PrivateFrameworks/CertUI.framework/CertUI
0x32541000 - 0x3254cfff  CommonUtilities armv7s  <9317cb2858663a8b872b5bcb11453aeb> /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
0x3254d000 - 0x32551fff  CommunicationsFilter armv7s  <53315d7fbfee3bf095fff818731fe781> /System/Library/PrivateFrameworks/CommunicationsFilter.framework/CommunicationsFilter
0x325e2000 - 0x325e4fff  ConstantClasses armv7s  <c910908091933017a5e778cb99a1b713> /System/Library/PrivateFrameworks/ConstantClasses.framework/ConstantClasses
0x328bb000 - 0x328d9fff  CoreServicesInternal armv7s  <6ccdd53c1e5a38f2b26689ef2c581e4d> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/CoreServicesInternal
0x328da000 - 0x328dbfff  CoreSurface armv7s  <19b928f48fd33cbe9a84800e6fd4f6cd> /System/Library/PrivateFrameworks/CoreSurface.framework/CoreSurface
0x32982000 - 0x329defff  CoreUI armv7s  <c7dc936e98b038eca494872b45cdac43> /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
0x32a34000 - 0x32a39fff  CrashReporterSupport armv7s  <ab302adde1ae3ae082fd79f8715c19fe> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
0x32c05000 - 0x32c1bfff  DataAccessExpress armv7s  <f00aabceb451315e992b17acf9cab9ba> /System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
0x32c61000 - 0x32c7afff  DictionaryServices armv7s  <09c74972d6f13eafad9eb92c90f75a71> /System/Library/PrivateFrameworks/DictionaryServices.framework/DictionaryServices
0x32cbf000 - 0x32ccafff  ExFAT armv7s  <487234d967b83efaac8ad7ad0222d8f1> /System/Library/PrivateFrameworks/ExFAT.framework/ExFAT
0x32d0a000 - 0x33125fff  FaceCore armv7s  <6f3ed32b715230269748ef8051d33dfd> /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
0x33501000 - 0x33517fff  GraphicsServices armv7s  <8f7e4b4580fb36ccbcefff542d4695ec> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x338c9000 - 0x33923fff  IMFoundation armv7s  <07c8a23c5c253572a879f67233353b2d> /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
0x3392d000 - 0x33934fff  IOMobileFramebuffer armv7s  <26b5badafbab334b8938ef2cc0bb294b> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
0x33935000 - 0x3393afff  IOSurface armv7s  <07af91d32c1a336f925dc4324cc5181f> /System/Library/PrivateFrameworks/IOSurface.framework/IOSurface
0x33d20000 - 0x33d2cfff  MobileAsset armv7s  <8285133654fa31b8bc1303b43952f32c> /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
0x33d77000 - 0x33d81fff  MobileKeyBag armv7s  <acdad27d6c0c3d6dbdb6e404247c36ef> /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
0x33da9000 - 0x33dacfff  MobileSystemServices armv7s  <8529e14b633933948a8973c0154889d7> /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
0x340a3000 - 0x340a5fff  OAuth armv7s  <320e2fa739c732f1bc7c24850c1b6d73> /System/Library/PrivateFrameworks/OAuth.framework/OAuth
0x347fc000 - 0x34837fff  OpenCL armv7s  <0688367e6d763081936b6f407caeaf09> /System/Library/PrivateFrameworks/OpenCL.framework/OpenCL
0x35220000 - 0x35253fff  PhysicsKit armv7s  <5238929b7609305ea9a207fd590b6ada> /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
0x3534a000 - 0x35381fff  PrintKit armv7s  <279bdf70cf1238769ca0daf119ed6af4> /System/Library/PrivateFrameworks/PrintKit.framework/PrintKit
0x35385000 - 0x3540bfff  ProofReader armv7s  <990f3fe1c1a53ed4800fa012f8de6a16> /System/Library/PrivateFrameworks/ProofReader.framework/ProofReader
0x357af000 - 0x357c4fff  SpringBoardServices armv7s  <514b46b2e3eb39baa809d3308020e30a> /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
0x35bdb000 - 0x35bddfff  TCC armv7s  <f6fded4db0b73c09ad14ae60ede0b74e> /System/Library/PrivateFrameworks/TCC.framework/TCC
0x35c31000 - 0x35c52fff  TelephonyUtilities armv7s  <f5f1551162fa3faaa8fef5a5df1ab422> /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
0x35fdd000 - 0x36010fff  TextInput armv7s  <9444551d85823650a01f79ec9ab31536> /System/Library/PrivateFrameworks/TextInput.framework/TextInput
0x36293000 - 0x36353fff  UIFoundation armv7s  <e1fd048ddb0c366f9641e26ad1ccc3c9> /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
0x3636b000 - 0x3636efff  UserFS armv7s  <c46624215c923567bc83abb4e8afa9aa> /System/Library/PrivateFrameworks/UserFS.framework/UserFS
0x36813000 - 0x372c3fff  WebCore armv7s  <95d5709defdf36929185826ce8e5b1c8> /System/Library/PrivateFrameworks/WebCore.framework/WebCore
0x372c4000 - 0x37384fff  WebKit armv7s  <912102708c63389faa548eae4f74781f> /System/Library/PrivateFrameworks/WebKit.framework/WebKit
0x374cf000 - 0x374d7fff  XPCObjects armv7s  <f27aaf4ae6ff32319064b8203000df15> /System/Library/PrivateFrameworks/XPCObjects.framework/XPCObjects
0x38303000 - 0x3830afff  libAccessibility.dylib armv7s  <317372be7093355da13230351e75862d> /usr/lib/libAccessibility.dylib
0x38507000 - 0x3851dfff  libCRFSuite.dylib armv7s  <ff8a959c51893b10b7b08a8a82cb00f4> /usr/lib/libCRFSuite.dylib
0x38533000 - 0x38548fff  libMobileGestalt.dylib armv7s  <60981e402d623a0d94c7b9f5c4ddbae1> /usr/lib/libMobileGestalt.dylib
0x38566000 - 0x38567fff  libSystem.B.dylib armv7s  <5c7ca1989cd733ad9d5cfd385d92876e> /usr/lib/libSystem.B.dylib
0x385d6000 - 0x38604fff  libTelephonyUtilDynamic.dylib armv7s  <e856eb67aff93c76ae2660a94b3e8a52> /usr/lib/libTelephonyUtilDynamic.dylib
0x38753000 - 0x3875ffff  libbsm.0.dylib armv7s  <fc1cbfcbdd563d02a601aabed2bd7d15> /usr/lib/libbsm.0.dylib
0x38760000 - 0x38769fff  libbz2.1.0.dylib armv7s  <20bf7a7ab7e73d4c8453b1c86a7c5e3d> /usr/lib/libbz2.1.0.dylib
0x3876a000 - 0x387b5fff  libc++.1.dylib armv7s  <72615c78ae5f39dcbafa740d87035caf> /usr/lib/libc++.1.dylib
0x387b6000 - 0x387d0fff  libc++abi.dylib armv7s  <b20ecbadceba32fe8f990af252b6abba> /usr/lib/libc++abi.dylib
0x387e0000 - 0x387e7fff  libcupolicy.dylib armv7s  <e085c6892cb7333a8b7e9adc2bda388f> /usr/lib/libcupolicy.dylib
0x38813000 - 0x38813fff  libgcc_s.1.dylib armv7s  <6a1193cb6ccd3e5a8c9b7bb8f65022ce> /usr/lib/libgcc_s.1.dylib
0x3882e000 - 0x3891bfff  libiconv.2.dylib armv7s  <cd99d67497e23173bfaf7eac2409774a> /usr/lib/libiconv.2.dylib
0x3891c000 - 0x38a6dfff  libicucore.A.dylib armv7s  <bbfd68a3928f3cacaf992982d12af10f> /usr/lib/libicucore.A.dylib
0x38a75000 - 0x38a75fff  liblangid.dylib armv7s  <3cca7b6ef834379b82d4a032f99cdfc8> /usr/lib/liblangid.dylib
0x38a76000 - 0x38a80fff  liblockdown.dylib armv7s  <401067be36cb34b9b89aa27e17640612> /usr/lib/liblockdown.dylib
0x38dff000 - 0x38f9efff  libobjc.A.dylib armv7s  <bf3e22d3067133989a99a9bf07c4e8f8> /usr/lib/libobjc.A.dylib
0x39066000 - 0x3907bfff  libresolv.9.dylib armv7s  <880b294be76f3f9989247ca125ad3550> /usr/lib/libresolv.9.dylib
0x390a4000 - 0x3913bfff  libsqlite3.dylib armv7s  <2bb2d0e7900a36d9a0a590bff69f3744> /usr/lib/libsqlite3.dylib
0x3913c000 - 0x39189fff  libstdc++.6.dylib armv7s  <6428df9b541c3ffbb23c393b3b1280e9> /usr/lib/libstdc++.6.dylib
0x3918a000 - 0x391b0fff  libtidy.A.dylib armv7s  <40c283e2258a330d9ff9799da0a1d2bb> /usr/lib/libtidy.A.dylib
0x391b4000 - 0x39267fff  libxml2.2.dylib armv7s  <1a18ebeae7253959b9cfe286550809a8> /usr/lib/libxml2.2.dylib
0x39268000 - 0x39289fff  libxslt.1.dylib armv7s  <cf7ad714d218330087df8422a129e027> /usr/lib/libxslt.1.dylib
0x3928a000 - 0x39296fff  libz.1.dylib armv7s  <578def3dfb6e3180b5f9d0cdacfea7ab> /usr/lib/libz.1.dylib
0x39297000 - 0x3929bfff  libcache.dylib armv7s  <5552b722402630c39069717fce563238> /usr/lib/system/libcache.dylib
0x3929c000 - 0x392a4fff  libcommonCrypto.dylib armv7s  <82710dcf6df73bfaa30b4639b23bef46> /usr/lib/system/libcommonCrypto.dylib
0x392a5000 - 0x392a9fff  libcompiler_rt.dylib armv7s  <b4b30a7810e13487b3fc8e7bc20058b7> /usr/lib/system/libcompiler_rt.dylib
0x392aa000 - 0x392b0fff  libcopyfile.dylib armv7s  <e1b229d8080f3d50bc2ed053fef9560b> /usr/lib/system/libcopyfile.dylib
0x392b1000 - 0x392eafff  libcorecrypto.dylib armv7s  <3078b6192ac6371eb233dfa9b483728b> /usr/lib/system/libcorecrypto.dylib
0x392eb000 - 0x392fefff  libdispatch.dylib armv7s  <8d674728d0e932779c2ea0df235fbc8e> /usr/lib/system/libdispatch.dylib
0x392ff000 - 0x39300fff  libdyld.dylib armv7s  <12c4e9c9e84e3795b4dd079293ca916e> /usr/lib/system/libdyld.dylib
0x39301000 - 0x39301fff  libkeymgr.dylib armv7s  <6694b9cf809236d1b82e54201aa0a26d> /usr/lib/system/libkeymgr.dylib
0x39302000 - 0x39308fff  liblaunch.dylib armv7s  <7f207c32352b3871b35d1c68643ef4ad> /usr/lib/system/liblaunch.dylib
0x39309000 - 0x3930cfff  libmacho.dylib armv7s  <287dff8dbe823694aa63c30f2356eae7> /usr/lib/system/libmacho.dylib
0x3930d000 - 0x3930efff  libremovefile.dylib armv7s  <dc132483942436c685800b7eb5cc74a2> /usr/lib/system/libremovefile.dylib
0x3930f000 - 0x3931cfff  libsystem_asl.dylib armv7s  <365d5b41bc363e999d096b6d14e704da> /usr/lib/system/libsystem_asl.dylib
0x3931d000 - 0x3931dfff  libsystem_blocks.dylib armv7s  <7df185e5c3423b2b827bbb017ae0d23a> /usr/lib/system/libsystem_blocks.dylib
0x3931e000 - 0x39380fff  libsystem_c.dylib armv7s  <5da46a1b062036f69c1932e4ec6695fb> /usr/lib/system/libsystem_c.dylib
0x39381000 - 0x39383fff  libsystem_configuration.dylib armv7s  <16eeedafa1813e2f987036af36fd194d> /usr/lib/system/libsystem_configuration.dylib
0x39384000 - 0x3938afff  libsystem_dnssd.dylib armv7s  <60599ab6fd903729b13814f32ab03e97> /usr/lib/system/libsystem_dnssd.dylib
0x3938b000 - 0x393a3fff  libsystem_info.dylib armv7s  <9a08ea9a5b853329bf15ed35fa7abb71> /usr/lib/system/libsystem_info.dylib
0x393a4000 - 0x393bcfff  libsystem_kernel.dylib armv7s  <f6ca1c52f11a332db664703eeffba463> /usr/lib/system/libsystem_kernel.dylib
0x393bd000 - 0x393dbfff  libsystem_m.dylib armv7s  <8b35d228991b344d917d09e78fdc1161> /usr/lib/system/libsystem_m.dylib
0x393dc000 - 0x393edfff  libsystem_malloc.dylib armv7s  <463678166dc632e7a84f363523b92b25> /usr/lib/system/libsystem_malloc.dylib
0x393ee000 - 0x3940efff  libsystem_network.dylib armv7s  <0daf6eb1b7eb3acfa8ff52b4f83188a3> /usr/lib/system/libsystem_network.dylib
0x3940f000 - 0x39416fff  libsystem_notify.dylib armv7s  <361750f2531d37a38030f6c772bc4a53> /usr/lib/system/libsystem_notify.dylib
0x39417000 - 0x3941bfff  libsystem_platform.dylib armv7s  <e04fc73de7d23ee9936a9411c3579196> /usr/lib/system/libsystem_platform.dylib
0x3941c000 - 0x39421fff  libsystem_pthread.dylib armv7s  <68c65cdd74da3a99b9cac14be055725c> /usr/lib/system/libsystem_pthread.dylib
0x39422000 - 0x39423fff  libsystem_sandbox.dylib armv7s  <1d88680294bd3086972849fa75229702> /usr/lib/system/libsystem_sandbox.dylib
0x39424000 - 0x39426fff  libsystem_stats.dylib armv7s  <19a6ad8a23b733eaa19241cab1d30d24> /usr/lib/system/libsystem_stats.dylib
0x39427000 - 0x39427fff  libunwind.dylib armv7s  <4b9e9973ab72392485a03ed5821f40a4> /usr/lib/system/libunwind.dylib
0x39428000 - 0x39442fff  libxpc.dylib armv7s  <6f447fba6cc7309c8c1c01c7bebf7060> /usr/lib/system/libxpc.dylib
]]></log><userid></userid><username></username><contact></contact><installstring>9A19995E-5DE4-456A-99A2-DD74D843691E</installstring><description><![CDATA[]]></description></crash>

**Comment by benstadin** [comment]
Sam for me.
