### ISSUE TITLE
multiple problems in develop branch (for server) and how to fix them

### ISSUE THREAD

**Issue by taoeffect** [bitstadium/QuincyKit#159]
don't want to send a PR because of how hackish the code is, but here's what you need to do to make the server stuff work:

**In `crash_v300.php`**
1. Your pgrep stuff is doing `$mail_activated = false;` when it shouldn't, and thus no emails are being sent.

**in `admin/common.inc` -> `groupCrashReport` function**
- you don't define enough globals, and this breaks everything. You are missing at least the following: 

``` php
global $dbversiontable, $dbgrouptable, $dbcrashtable, $dbsymbolicatetable, $notify_default_version, $notify_amount_group, $push_activated, $boxcar_activated, $mail_activated, $mail_from, $notify_emails, $applicationname, $crash_url, $crash_offset;
```
- `$notify_amount_group == $amount` should be `$amount <= $notify_amount_group`
- in this same function you do `mysql_free_result($result);`, but that is wrong because at one point $result is a boolean, not a result set (that happens when you're inserting/updating)
- you aren't doing any error logging, but you should, especially if it fails to send the email.

**in `config.php.sample`**
- `boxcar_activated` should be false by default

**Comment by just-doit** [comment]
Hi,
I think $notify_amount_group == $amount is correct because the email should only be send if the configured amount of crashes is reached.
