### ISSUE TITLE
CrashDemo works Fine with Simulator Not in Device(Jail Broken):-

### ISSUE THREAD

**Issue by karthikeyanvijayan** [bitstadium/QuincyKit#16]
Hii People,

 Thanks for this Library and i have integrated into my app but the crash alert works only in simulator and not in device and i want to know whether it supports only real devices!

**Comment by DerAndereAndi** [comment]
Hi,

I don't get what you mean because you state twice the opposite :) It does work on real devices only, since the way PLCrashReporter catches the crash does not work in the simulator!

Andreas

**Comment by dorianj** [comment]
Andreas -- PLCrashReporter works fine for me in the simulator. I've not tried CrashReporterDemo in the simulator, but my demo app does work. Not sure why it wouldn't work for you?

**Comment by DerAndereAndi** [comment]
I think I just got confused by the issue description which doesn't make sense at all.
