### ISSUE TITLE
15 wakes in 300 sec crash handling

### ISSUE THREAD

**Issue by vishnu-mee** [bitstadium/QuincyKit#161]
@TheRealKerni  I have a doubt the crash reporter framework works fine for crashes occurred from app.But will it be able to handle the crash which is due to iOS killing the app after 15 wakes in 300 seconds in background.Any help is appreciated.

**Comment by DerAndereAndi** [comment]
The short answer: no 3rd party crash report can do that.

Long answer: If an app gets killed by the system, the actual app process that gets killed doesn't get any information about that prior to the kill action. Hence it is not possible for a crash reporter that runs in the same process as the app to detect such crashes.

**Comment by vishnu-mee** [comment]
Is there an alternate way to handle the system kill.

**Comment by DerAndereAndi** [comment]
No.

**Comment by vishnu-mee** [comment]
Will crash handler be able to report crash when the crash handler itself is responsible for the crash(due to code deprecation and lack of SDK support in future)

**Comment by DerAndereAndi** [comment]
The crash handler has no known issues or limitations due to code deprecation or lack of SDK support in the future. If you have further questions, please be more specific.
