### ISSUE TITLE
BWQuincyManager init is failed

### ISSUE THREAD

**Issue by NarsuAltan** [bitstadium/QuincyKit#163]
The QuincyKit demo runs perfectly fine and I can see the crash report;
but when i integrated QuincyKit to my own project, all allocations failed in method init of BWQuincyManager.
(
    start from line 185:
    _approvedCrashReports = [[NSMutableDictionary alloc] init];
    _fileManager = [[NSFileManager alloc] init];
    _crashFiles = [[NSMutableArray alloc] init];
    //after the allocation _approvedCrashReports,_fileManager and _crashFiles are all nil;
)
here is what i did:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {    
  
  // Override point for customization after application launch.
  [[BWQuincyManager sharedQuincyManager] setSubmissionURL:@"http://172.20.0.58/crash_v300.php"];
  [[BWQuincyManager sharedQuincyManager] setDebugLogEnabled:YES];
  [[BWQuincyManager sharedQuincyManager] setAutoSubmitCrashReport:NO];
  [[BWQuincyManager sharedQuincyManager] startManager];
  ....
  }

i couldn't really figure out what's wrong with my code
thanks for all your help.

**Comment by fishkingsin** [comment]
+1 encounter this issue
please help

**Comment by fishkingsin** [comment]
quick fix 

added 

```
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);
    _crashesDir = [[paths objectAtIndex:0] stringByAppendingPathComponent:@"/crashes/"];
```

before 

```
  if ([_fileManager fileExistsAtPath:_crashesDir]) {
```

**Comment by fishkingsin** [comment]
and other quick fix
line 267
add

```
 _settingsFile = [_crashesDir stringByAppendingPathComponent:@"quincykit.settings"];
```

to

```
if (plist) {
    _settingsFile = [_crashesDir stringByAppendingPathComponent:@"quincykit.settings"];
    [plist writeToFile:_settingsFile atomically:YES];
  } else {
    BWQuincyLog(@"ERROR: Writing settings. %@", errorString);
  }
```
