### ISSUE TITLE
Fix: symbolicatecrash.pl freezes on crash with multiple identical image lines

### ISSUE THREAD

**Issue by sevaa** [bitstadium/QuincyKit#170]
Symbolicate would freeze when there are several identical lines for the same binary image. I'm not sure what I'm doing, but I've isolated it down to an endless loop and inserted an alternative exit condition. The function is parse_images, and the relevant spot is:

```
            # follow the chain of hash items until the end
            my $nextIDKey = $bundlename;
            while ( length($nextIDKey) ) {
                last if ( !length($images{$nextIDKey}{nextID}));
                $nextIDKey = $images{$nextIDKey}{nextID};
            }
```

This loop never ends on several of my crashes. They have numerous identical lines for AssetCacheServices.

I've replaced the if line before the loop to ignore duplicate lines, from

```
lif ( defined($images{$bundlename}) ) {
```

to

```
  if ( defined($images{$bundlename}) && $images{$bundlename}{base} ne $image{base} ) {
```

**Comment by mhstnsc** [comment]
http://stackoverflow.com/questions/31920423/ios9-duplicated-lines-in-crash-reports-are-causing-symbolicatecrash-to-get-stuc
