### ISSUE TITLE
Extra space in symbolicate.php causes lighttpd to return 400 when remote symbolicating

### ISSUE THREAD

**Issue by echamberlain** [bitstadium/QuincyKit#18]
Hello,

We are using lighttpd as our web server and when symbolicate.php tries to upload the symbolicated crash log, the server returns a 400 Bad Request due to an extra space in the POST header.

Here is a diff of symbolicate.php that fixes the problem:

<pre>
diff --git a/server/local/symbolicate.php b/server/local/symbolicate.php
index 9858383..7ef767c 100644
--- a/server/local/symbolicate.php
+++ b/server/local/symbolicate.php
@@ -50,7 +50,7 @@ function doPost($postdata)
                return 'error'; 
        } 
        else { 
-               $temp = "POST ".$uri."  HTTP/1.1\r\n"; 
+               $temp = "POST ".$uri." HTTP/1.1\r\n"; 
                $temp .= "Host: ".$host."\r\n"; 
                $temp .= "User-Agent: PHP Script\r\n"; 
                $temp .= "Content-Type: application/x-www-form-urlencoded\r\n";
</pre>

**Comment by DerAndereAndi** [comment]
Thanks for the patch, I just applied it to the develop branch.
