### ISSUE TITLE
Leaks in CrashReportSender.m?

### ISSUE THREAD

**Issue by echamberlain** [bitstadium/QuincyKit#19]
Hi,

When I run a Build and Analyze on the CrashReportDemo code, Xcode flags some memory leaks and warnings in CrashReportSender.m.

<pre>
/CrashReporterDemo/iPhone/Classes/CrashReportSender.m:316:1: warning: Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred
 - (void)parseXMLFileAtURL:(NSString *)url parseError:(NSError **)error
 ^
/CrashReporterDemo/iPhone/Classes/CrashReportSender.m:706:3: warning: Potential leak of an object allocated on line 706
         [[NSURLConnection connectionWithRequest:request delegate:self] retain];
          ^
/CrashReporterDemo/iPhone/Classes/CrashReportSender.m:777:22: warning: Potential leak of an object allocated on line 777 and stored into 'crashData'
         NSData *crashData = [NSData dataWithData:[crashReporter loadPendingCrashReportDataAndReturnError: &error]];
                             ^
3 warnings generated.
</pre>

Are those extra retains really needed?

**Comment by DerAndereAndi** [comment]
All fixed in the develop branch
