### ISSUE TITLE
Invalid OS Version String crashes symbolicatecrash

### ISSUE THREAD

**Issue by hhessel** [bitstadium/QuincyKit#2]
xxx-MacBook:WhereAreYou1_04 xxx$ symbolicatecrash 2010-07-29\ 20-07-32.crash 
Error: can't parse OS Version string iPhone OS 4.0 at /usr/local/bin/symbolicatecrash line 632.

correct string (taken from xcode)  iPhone OS 4.0 (8A293)

**Comment by DerAndereAndi** [comment]
Please try the custom version of the symbolicatecrash script: http://gist.github.com/316924

**Comment by hhessel** [comment]
Doesn't work either :( 

$perl symbolicatecrash.pl 2010-07-29\ 20-41-11.crash WhereAreYou.app.dSYM/
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.
Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144.

**Comment by DerAndereAndi** [comment]
Those warnings are no problem. There is no need to add the dsym into the path, simply invoke it by using "./symbolicatecrash 2010-07-29\ 20-41-11.crash"

If nothing gets symbolicated, try adding the option "-v" before the crash filename to see the important error messages.

**Comment by hhessel** [comment]
Thanks for your continuous support. I think the root of the problem is here:

Searching in Spotlight for dsym with UUID of /var/mobile/Applications/C0FDDF92-6B6B-4491-B7C7-1C8F42243BD4/WhereAreYou.app/WhereAreYou
Running mdfind "com_apple_xcode_dsym_uuids == F95BCA7B-7757-CD2F-BD50-F83E14696DD4"
dsym directory: \/Users\/xxx\/Documents\/XCode\/productive\/Crashreports\/WhereAreYou1_04\/WhereAreYou.app.dSYM\
\/Users\/xxx\/Library\/MobileDevice\/Archived\ Applications\/65A6A1FC-282B-43CC-802C-32208001964D\/WhereAreYou.app.dSYM\
\/Users\/xxx\/Documents\/XCode\/productive\/WhereAreYou\/build\/Release-iphoneos\/WhereAreYou.app.dSYM
paths: /Users/xxx/Documents/XCode/productive/Crashreports/WhereAreYou1_04/WhereAreYou.app/ /Users/xxx/Documents/XCode/productive/Crashreports/WhereAreYou1_04/WhereAreYou.app/WhereAreYou /Users/xxx/Documents/XCode/productive/Crashreports/WhereAreYou1_04/WhereAreYou.app/Contents/MacOS/WhereAreYou
Given UUID f95bca7b7757cd2fbd50f83e14696dd4 for '/Users/xxx/Documents/XCode/productive/Crashreports/WhereAreYou1_04/WhereAreYou.app/WhereAreYou' is really UUID 63c02d606a2959f7a1dfa0bd711e3dc5
UUID doesn't match dsym for executable /Users/xxx/Documents/XCode/productive/Crashreports/WhereAreYou1_04/WhereAreYou.app/WhereAreYou
Did not find executable for dsym

## Warning: Can't find any unstripped binary that matches version of /var/mobile/Applications/C0FDDF92-6B6B-4491-B7C7-1C8F42243BD4/WhereAreYou.app/WhereAreYou

**Comment by DerAndereAndi** [comment]
Yep, so the symbolication should work in general, if you have the correct binary and the corresponding .dsym file

**Comment by hhessel** [comment]
Yeah, I'm not that stupid. I used the Build and Archive -> Reveal in Finder and copied the .app + .dysm file to a separated folder (which can be found by spotlight). Strange that xcode generates two different UUID for each file Oo

**Comment by DerAndereAndi** [comment]
I did not mean to imply that. But having different UUIDs is really strange. I never used that feature though, did my own backup implementation months ago before that feature was available.

**Comment by ChronicStim** [comment]
Hi Guys. Just downloaded the latest project files and I'm still getting errors when trying to symbolicate the crash reports. The specific error is as follows:

Processing crash id 25 ...
  Downloading crash data ...
  Writing log data into temporary file ...
  Symbolicating ...
Use of uninitialized value in length at ./symbolicatecrash line 663.
...
Use of uninitialized value in length at ./symbolicatecrash line 663.
Use of uninitialized value in length at ./symbolicatecrash line 663.
Error: can't parse OS Version string Mac OS X 4.0 at ./symbolicatecrash line 632.
  Deleting temporary files ...

Warning: unlink(result_25.crash): No such file or directory in /Users/bkutschke/Documents/MyApps/CrashReports/symbolicate.php on line 154

Done

bash-3.2$

**Comment by DerAndereAndi** [comment]
Is this iOS or Mac? Which version of symbolicatecrash are you using?

For testing I recommend downloading a crash file to your desktop and try to execute symbolicatecrash in the terminal.

**Comment by hhessel** [comment]
Did anyone here installed the XCode 4 Beta? Might be the source for several problems.

**Comment by DerAndereAndi** [comment]
I haven't tested XCode 4 yet, it is installed, but in another directory where it cannot harm production. I will check it out asap.

**Comment by ChronicStim** [comment]
Sorry, I should have been more clear. I am trying the iPhone project for iOS 4. I'm using xcode 3.2.3 with the project base sdk set to iPhone Device 4.0. I'm building and running on the iphone simulator in debug mode. I run the app and hit crash button. Then run it again and select YES to send the crash report.

It works fine getting it to my web server and I can download it to my desktop and run the following: symbolicatecrash -o -v [crash report name]

That's when I get the error. BTW, I get the same results if I try to use the scripts by running "php symbolicate.php" in X11.

**Comment by DerAndereAndi** [comment]
Did you try using the patched symbolicatecrash script at http://gist.github.com/316924 ? Or are you using the version provided by XCode?

**Comment by ChronicStim** [comment]
I was using the one that I found here: /Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/DTDeviceKit.framework/Versions/A/Resources/symbolicatecrash

I'll try the other one, but can you explain how to handle it? Once I expand the tar, I've got a folder with the file "symbolicatecrash.pl supporting...." Do I just rename that to symbolicatecrash OR symbolicatecrash.pl OR do I need to do something else before using?

**Comment by hhessel** [comment]
"chmod +x symbolicatecrash.pl" and then "perl symbolicatecrash.pl mycrash.crash"

**Comment by DerAndereAndi** [comment]
1. Please use the patched version I linked above
2. Symbolicating crashes from the iPhone Simulator does not work, since the crashlog file is formatted for the arm architecture crashlog file format. Also, this is not really required to work, since XCode does symbolicate those crashes right away without the need of this library.

**Comment by hhessel** [comment]
@TheRealKerni I can grant you access to my MacBook. I think I've got the same problem like ChronicStim. hhessel@web.de ... I'm german too ;)

**Comment by ChronicStim** [comment]
I'll give the patched version a try and run from device rather than simulator. Will let you know. Thanks for the assistance.

**Comment by ChronicStim** [comment]
Hey, that worked (mostly). I did end up with a symbolicated crash report, although the script through a couple of errors as follows:

Use of uninitialized value in concatenation (.) or string at symbolicatecrash.pl line 144. {this line was repeated 16 times}
Use of uninitialized value in string eq at symbolicatecrash.pl line 707. {this line was repeated 6 times}

These appeared first in terminal and then it spit out the symbolicated report.

What is required to modify the symbolicate.php script to use the new perl script?

**Comment by DerAndereAndi** [comment]
Those warnings are not important. Apple bugs :)

All I did is copy the patched symbolicatecrash.pl file somewhere into the PATH, like /usr/bin
Make sure to do "chmod +x ..." as hhessel mentioned above and validate it is accessing the correct one by typing "which symbolicatecrash" which should show /usr/bin/symbolicatecrash

**Comment by ChronicStim** [comment]
Okay. I actually modified the symbolicate.php script as follows:

```
        exec('perl '.'./symbolicatecrash.pl -o '.$resultfilename.' '.$filename);
```

which seems to work fine when I ran it.

Thanks again for the help guys.

**Comment by mikebevz** [comment]
Patched version worked well. The only problem that symbolicate.php refers to ./symbolicatecrash so I had to create symbolic link to /usr/local/bin
Otherwise I'm so happy with your tool! ;)

**Comment by mapedd** [comment]
hi, andreas
i'm trying to symbolicate crash log. when i'm doing it with symbolicatecrash copied from xcode4 directory it shows error: 
<b>
Use of uninitialized value in length at /usr/local/bin/symbolicatecrash line 684.
Error: can't parse OS Version string iPhone OS 4.3.1 at /usr/local/bin/symbolicatecrash line 654.</b>

when i'm trying to do that with your patched version, it show valid symbols in console, but it don't write it anywhere, so that i cant upload anything to the server, any toughts?

i don't know if it really matters but i have installed xcode3 in /Developer and xcode4 in /Developer4

**Comment by DerAndereAndi** [comment]
Please follow these steps: https://github.com/TheRealKerni/CrashReporterDemo/wiki/Remote-symbolication

**Comment by mapedd** [comment]
I did that, but crashlog on the server is not symbolicated, performing <b>php symbolicate.php</b> products following console log:

<b>
To do list: 5,10

Processing crash id 5 ...
  Downloading crash data ...
  Writing log data into temporary file ...
  Symbolicating ...
sh: ./symbolicatecrash: No such file or directory
  Deleting temporary files ...

Warning: unlink(result_5.crash): No such file or directory in /Users/test/Desktop/Symbolification/symbolicate.php on line 154
Processing crash id 10 ...
  Downloading crash data ...
  Writing log data into temporary file ...
  Symbolicating ...
sh: ./symbolicatecrash: No such file or directory
  Deleting temporary files ...

Warning: unlink(result_10.crash): No such file or directory in /Users/test/Desktop/Symbolification/symbolicate.php on line 154

Done

</b>

**Comment by DerAndereAndi** [comment]
The php script is invoking symbolicatecrash from its current directory: `./symbolicatecrash: No such file or directory`

So you obviously forgot to store the patched version in that directory and/or to give it execution rights.

**Comment by mapedd** [comment]
i've downloaded patched version, named it symbolicatecrash.pl and make <b>chmod +x</b> on it, and this file is present in the current directerory, nevertheless making <b>which symbolicatecrash</b> it points to usr/local/bin/symbolicatecrash  

does script in symbolicate.php know to use this patched version? ( i know completely zero from php :( )

**Comment by mapedd** [comment]
ok, i've changed <b>exec('./symbolicatecrash</b> to <b>exec('./symbolicatecrash.pl</b> in symbolicate.php and it worked:D 
thanks again for this awesome framework!
