### ISSUE TITLE
CrashReporterDemo web interface SQL injection vulnerability.

### ISSUE THREAD

**Issue by echamberlain** [bitstadium/QuincyKit#20]
The CrashReporterDemo web interface does not escape the description text before writing to the database.

To see an example of this problem, put a ' in the group description text and click update.

A SQL error is returned.  The form text should not be directly sent to the database as this opens the server up to SQL injection attacks.

**Comment by DerAndereAndi** [comment]
Thanks for the hint, fixed in the develop branch.
