### ISSUE TITLE
Bad Request from symbolicate.php

### ISSUE THREAD

**Issue by Dukeman330** [bitstadium/QuincyKit#22]
I'm getting a "Bad Request" whenever I try to re-upload symbolicated crash files to the server.  Specifically, doPost is returning the following result:

400 Bad Request
Your browser sent a request that this server could not understand.
Client sent malformed Host header

The header data that's actually generated (with my URL edited out) is:

POST /admin/crash_update.php  HTTP/1.1
Host: http://[my still-in-develpoment site]/crashreporter
User-Agent: PHP Script
Content-Type: application/x-www-form-urlencoded
Content-Length: 14858
Connection: close

Any idea how this is getting malformed?

**Comment by DerAndereAndi** [comment]
Could this be related to this issue?

https://github.com/TheRealKerni/CrashReporterDemo/issues#issue/18

**Comment by Dukeman330** [comment]
Ah, that wasn't the issue, but it turns out it was a mistake on my end.  I had the admin folder in /crashreporter/admin on my server.  Trouble is, I'd input the hostname variable as www.[host].com/crashreporter, rather than appending it to the appropriate URL paths.  My bad.
