### ISSUE TITLE
Weak Using the Reachability class

### ISSUE THREAD

**Issue by monkeydom** [bitstadium/QuincyKit#25]
On iOS people might have (i did) used the Reachability sample code as basis and not renamed the class, if so Quincy crashes on reporting because of that. Which reachability class are you expecting to have there? If it is a class you implement yourself, prefixing it would be recommended

**Comment by DerAndereAndi** [comment]
The relevant code is this:

```
    NSInteger networkStatus;
    SEL currentReachabilityStatusSelector = NSSelectorFromString(@"currentReachabilityStatus");
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[reachability methodSignatureForSelector:currentReachabilityStatusSelector]];
    invocation.target = reachability;
    invocation.selector = currentReachabilityStatusSelector;
    [invocation invoke];
    [invocation getReturnValue:&networkStatus];

    // 0 = NotReachable
    BOOL isOffline = networkStatus == 0;
```

So if the `networkStatus` value is the same and `currentReachabilityStatus` returns the same, no change should be required.

**Comment by DerAndereAndi** [comment]
Ok, understood the issue. Just added some updates to fix this issue. Quincy now listens to a notification `NetworkDidBecomeReachable` that you need to send yourself in your reachability code. Quincy will pick this up and try to send pending crashreports.

**Comment by DerAndereAndi** [comment]
Implemented a while ago :)
