### ISSUE TITLE
fix_status report is always returned as unknown ?

### ISSUE THREAD

**Issue by airy10** [bitstadium/QuincyKit#27]
It seems the fix_status report after crash submission is broken. I always get "unknown".
My php knowledge is close to 0 but moving the $best_status update from the loop at the bottom of crash_v200.php to the crash analyzer loop seems to fix it for me.
I'm guessing "foreach ($crashes as $crash)"  is putting some copy into $crash so updating $crash doesn't update the array (wild guess from knowing nothing about php)...

**Comment by DerAndereAndi** [comment]
Thanks for the bug report. Actually it was kinda silly to set the values in another loop. Changed it according to your suggestion. Please fetch the latest code and retry to make sure it is fixed for you.

**Comment by airy10** [comment]
works great - thanks
closing the issue
