### ISSUE TITLE
Feature Request: more info flag

### ISSUE THREAD

**Issue by foozmeat** [bitstadium/QuincyKit#30]
We currently don't show the initial crash dialog in Prompt (our iOS app) so reports are sent silently. We aren't currently collecting an email address either. We'd like to be able to flag a crash as needing more info. If a crash needs more info then when a user encounters this crash the server would send back a status indicating this. They would then get a dialog that asks for an email address and more details.

I haven't thought about the implications this would have for the mac app but it could perhaps show different text on the crash dialog indicating that we're really interested in this particular crash and would really like more details.

I may start working on this myself unless it's something you have in the pipeline.

**Comment by DerAndereAndi** [comment]
Hi James,

this sounds pretty interesting. I have a few questions and thoughts:
- This would also mean that the current feedback feature should be disabled if this is used, otherwise a dialog with an information like "thanks for the report. a new version is available in the AppStore" would come out of the dark, since the user never approved sending an report
- Would every new crash that belongs to the flagged group get that question? Or should it be limited to 1 or any other amount?

What I was thinking about to add in the future, is a better option to automatically add log information into the description field of the XML structure. But that requires the developer to add such information while the app is running. Like adding the system.log output (the Mac version can do that already).
On the Mac this would also mean, that the user won't get asked on the next startup, but a similar dialog should appear while the app is running.

We could work on that together, because we would love to add that also to our HockeyApp service.

Andreas

**Comment by foozmeat** [comment]
Actually this is how we're using it.

1) crash reports are sent silently
2) users are notified of the fix status of crashes

This way the only time they get a dialog is with some kind of good news.

What I'm working on right now is a crash group flag that let's the app know that we need more info about a crash. Once a crash is submitted the server returns a 5 (CRASH_STATUS_MORE_INFO). This will show a dialog telling the user that we need more info on this particular crash and it'll have a Cancel and Email button. The Email button will start a new email with some relevant information in the body and a place for them to add comments. So, they'll only get bothered with a dialog if we need more info OR we have some good news for them.

## 

James

**Comment by DerAndereAndi** [comment]
Sounds good. I wonder if it would be nice to show a dialog instead of the email form to also send the data to the database. The information could be either added to the crash report description field or to to crash group description. So everything stays in the system. What do you think?

**Comment by foozmeat** [comment]
I was originally thinking about doing that but this gives our tech support a chance to have a conversation with the user. I also didn't like the idea of creating new UI for the comment box. The email experience should feel smoothest in the end I think.

There's also the server-side problem of locating the crash that was just submitted and updating it. Unless, the workflow is changed such that the app talks to the server to get the more_info_status before submitting but that seems cumbersome to me.

## 

James

**Comment by DerAndereAndi** [comment]
Well, the additional UI surely is a little more work. I might be able to take a look at that after WWDC. I should have said it differently I guess: those two peaces of information should be linked somehow. So the mail should when received contain a link to the corresponding crash group. But the problem on that part is most likely how to insert the link after the user taps the send button. And when viewing the crash groups, it should be helpful not only to see, that the flag is set, but also that additional information has been gathered and where to find it.

I agree that the workflow right now doesn't fit that very well. Maybe I'll figure something out, or someone else :) Thanks already for all your additions and ideas, great stuff!

**Comment by foozmeat** [comment]
Hey Andreas, I finally got around to finishing this. Take a look at my more_info branch.

**Comment by DerAndereAndi** [comment]
Hi James,

I took a quick look. Are you sure you want to use a mail sheet? This way you would loose the direct link to the crash group.

**Comment by DerAndereAndi** [comment]
Hi James,

I merged your changes into a new branch https://github.com/TheRealKerni/QuincyKit/tree/feature/21 and made some tiny adjustments.

I am not sure about the email setting, adding its own message window would be quite some more code, but it would allow us to add the comment to the actual crash report. What do you think?

Thanks
Andreas

**Comment by foozmeat** [comment]
It's unlikely we'll add a stand-alone message editor. We may ask the user for their email address after they hit the first crash. That should allow us to send it along with the crash report right?
