### ISSUE TITLE
Linker error under iOS 4.3

### ISSUE THREAD

**Issue by cwoloszynski** [bitstadium/QuincyKit#31]
I am working to incorporate this into my project and I have run into a linker error.  I downloaded the PLCrashReporter code and  built it.  I think incorporated that framework into my project.  I then added your client code.  

Now when I try to link the code, I get an error  

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_PLCrashReporter", referenced from:
      objc-class-ref in synergyAppDelegate.o
  "_OBJC_CLASS_$_PLCrashReport", referenced from:
      objc-class-ref in synergyAppDelegate.o
ld: symbol(s) not found for architecture i386
collect2: ld returned 1 exit status

Is this package expected to be able to be run under the simulator, or only on ARM devices?  I'd like to be able to build it for either device and have it run (even if the crash reporter won't catch anything on the x86).

Am I using this wrong or expecting something it cannot handle?

Thanks in advance,

Charlie

**Comment by DerAndereAndi** [comment]
Hi Charlie,

PLCrashReporter can be build for device and simulator. So when building the framework make sure the target is set to build for all architectures. E.g. the default debug setting builds only for the default architecture.

But why are you trying to build PLCrashReporter yourself? The provided build works pretty fine, and Landon will provide a newer version soon. You shouldn't use trunk unless you are prepared to be developer of that one too :)

Andreas

**Comment by cwoloszynski** [comment]
First, thanks for getting back to me so quickly. 

I looked at the 1.0 version but that was from sept 09 and it looked like the SVN repository had many fixed since then. So I thought I'd use the latest. Is that a bad idea?  

I'll look into the build targets to get the right stuff in there. 

Charlie

**Comment by DerAndereAndi** [comment]
Charlie,

yes, we'd say  this is a bad idea. Don't use version 1.0 of PLCrashreporter, use the one being part of this repository, it works well enough for everybody. The new version will have some fixes and new features, but nothing which can't wait for an official release. I am also using the version provided in this repository, so are all others I know of.

Andreas

**Comment by cwoloszynski** [comment]
I really prefer to have the source. Do you know what revision was used to build that one?

Charlie

**Comment by DerAndereAndi** [comment]
I think the revision is 316

**Comment by cwoloszynski** [comment]
Thanks. 

I guess I'll follow your lead on the binary package. I tried to get the build scripts to work for me, but I have a case sensitive Filesystem (which is not standard but available on macosx, i use it for Linux work). Anyway, the build scripts switch between iPhoneOS and iphoneos, etc. Looks like a longer project than I wanted. 

Thanks for the help. If you do move to a new version of Plcrashreporter, I am interested to know the version and the changes you make to the build script to get it to work. Like to change from 10.5 to 10.6, etc. 

Thanks. 

Charlie
