### ISSUE TITLE
CrashDataFoundDescription is missing stringWithFormat

### ISSUE THREAD

**Issue by hongrich** [bitstadium/QuincyKit#32]
Looks like app name is added to the strings file in this commit, but there's nothing in the code to format CrashDataFoundDescription.
https://github.com/TheRealKerni/QuincyKit/commit/b0d88d61fb1c2023134257d6f4837534ae9e3698

**Comment by DerAndereAndi** [comment]
Good catch, must have missed it while merging. I fixed it and also removed the language files which do not fit the current format.
