### ISSUE TITLE
Cannot Symbolicate on iOS 4.3.3

### ISSUE THREAD

**Issue by rileytestut** [bitstadium/QuincyKit#33]
When using the code as-is, whenever I try to symbolicate the crash files, I receive the error:

Error: can't parse OS Version string iPhone OS 4.3.3

I have found that the way to fix it is to manually change the "OS Version" on my server (in the log) from "iPhone OS 4.3.3"  to "iPhone OS 4.3.3 (8J2)", so I'm essentially adding the build version just like a normal crash report. I have also found if I put anything else in the parenthesis (such as "test"), it will symbolicate my app functions, but no system functions.

Right now, the only way to fix this would be to hard code every iOS version and its build number so I can get all the information. This obviously will be a huge hassle whenever an iOS update comes out (even small ones).

What can I do to get it to work?

**Comment by DerAndereAndi** [comment]
The README.markdown (https://github.com/TheRealKerni/QuincyKit/blob/develop/README.markdown) and the wiki (https://github.com/TheRealKerni/QuincyKit/wiki/Remote-symbolication) contain instructions on how to do that by using a linked modified symbolication script.

**Comment by rileytestut** [comment]
Thanks that was it! I was following the instructions in the README.markdown under the heading "SETUP LOCAL SYMBOLIFICATION", which does NOT say to turn the symbolicatecrash into an executable, but I should've been able to figure that one out anyway.
