### ISSUE TITLE
Duplicate symbol during linking

### ISSUE THREAD

**Issue by InfiniteLoopDK** [bitstadium/QuincyKit#34]
I'm currently incorporating QuincyKit services into my iPhone app but have run into a problem with duplicate symbols for protobuf_c_service_destroy when linking in QuincyKit/CrashReporter.framework: 

_ld: duplicate symbol _protobuf_c_service_destroy in /Users/broch/Documents/Source/YourRound/3rdParty/QuincyKit/client/iOS/CrashReporter.framework/CrashReporter(protobuf-c.o) and /Users/broch/Documents/Source/YourRound/3rdParty/Bump/API_build/libBumpAPI.a(protobuf-c.o) for architecture armv6_

Is there anyway you could namespace your usage of the Protocol Buffers so these two can co-exist?

**Comment by DerAndereAndi** [comment]
Hi, you should ask the developer of PLCrashReporter for that: http://code.google.com/p/plcrashreporter/

**Comment by InfiniteLoopDK** [comment]
Ahh, you're right. I'll do that.

**Comment by landonf** [comment]
As Andreas noted, I need to re-enable stripping of these symbols in PLCrashReporter. However, as a temporary work-around you can use:

```
cd CrashReporter.framework
mv CrashReporter CrashReporter.bak
perl -n -p -e 's/protobuf/xrotobuf/g' < CrashReporter.bak > CrashReporter
```

**Comment by InfiniteLoopDK** [comment]
Thanks Landon, I'll try the workaround.
BTW since you have commented on this thread, I presume I don't have to open an issue on your repository :)

**Comment by InfiniteLoopDK** [comment]
@landonf Just a quick brush-up to let you know your suggested work-around worked like a charm.

Thanks for the help.
