### ISSUE TITLE
reference to native symbolicatecrash in php

### ISSUE THREAD

**Issue by abeazam** [bitstadium/QuincyKit#37]
to get the symbolicatecrash working locally i had to update symbolicate.php line 313 from:

exec('./symbolicatecrash -o '.$resultfilename.' '.$filename);
to
exec('perl ./symbolicatecrash.pl -o '.$resultfilename.' '.$filename);

abe

**Comment by DerAndereAndi** [comment]
Right, good point. Otherwise the user would have to do a chmod +x first. Gonna change it.
