### ISSUE TITLE
Downloading wrong crash data

### ISSUE THREAD

**Issue by dannybabiy** [bitstadium/QuincyKit#44]
After setting up the php server and playing around with some tests, I deleted an app from the admin console along with some other test crashes.  Now I have one app with one crash report.  When I try to run php symbolicate.php locally it spits out that its trying to process a bunch of crash ids (guessing the deleted ones), and then only finds one valid one to download.  The problem is, the one valid one that it finds is actually an old deleted one.  For some reason it doesn't seem to download the one valid one thats actually on the server.

**Comment by dannybabiy** [comment]
Oh, so I realized I wasn't using the latest source. With the latest the one old crash report at least got deleted after failing to symbolicate.  So now i'm at a state where it simply doesn't find the valid crash report at all.

To do list: 4,3,5,11,10,12

Processing crash id 4 ...
  Downloading crash data ...
Processing crash id 3 ...
  Downloading crash data ...
Processing crash id 5 ...
  Downloading crash data ...
Processing crash id 11 ...
  Downloading crash data ...
Processing crash id 10 ...
  Downloading crash data ...
Processing crash id 12 ...
  Downloading crash data ...

Done

**Comment by dannybabiy** [comment]
OOOH... so I guess I needed to press symbolicate in the admin view just so the local call would grab it.  Thats not very intuitive and should probably be listed in the docs somewhere.  I thought pressing symbolicate on the server is for once you upload all the "local" stuff to the server.  But now I see thats not the case.

**Comment by DerAndereAndi** [comment]
One addition: You can set in the admin UI per app, if each incoming crash should be symbolicated or not, instead of having to activate symbolication for each crash individually.
