### ISSUE TITLE
Uploading logs

### ISSUE THREAD

**Issue by rnapier** [bitstadium/QuincyKit#45]
There doesn't currently appear to be a way to upload logs or other program-provided data along with the crash report.

**Comment by DerAndereAndi** [comment]
Upload Logs: Do you mean uploading manually? No, there is not. But it should be fairly easy to add. Feel free to provide some patches.

Program-provided data: Check the BWQuincyManagerDelegate methods. You might be interesting in implementing crashReportDescription to provide any additional textual data you want.

Best
Andreas
