### ISSUE TITLE
Only Symbolicating System Methods (like UIKit)

### ISSUE THREAD

**Issue by rileytestut** [bitstadium/QuincyKit#46]
Previously, I was able to use this fine and it would symbolicate every line of the crash logs. Now, it's only symbolicating methods that belong to the system frameworks, such as UIKit.

I did mess with some settings for it to work with Testflight, but I have reverted them all back. These are the settings in question and what they are set to now:

Generate Debug Symbols: Yes
Debug Information Format: DWARF with dSYM File
Deployment Postprocessing: Yes
Strip Linked Product: Yes
Use Separate Strip: Yes
Strip Debug Symbols During Copy: No
Strip Style: All Symbols

Any other settings that could be messing it up?

**Comment by DerAndereAndi** [comment]
In my default settings I have 2 differences:

Use Separate Strip: No
Strip Debug Symbols During Copy: Yes

But both should not have an effect on symbolication, since those only say if/how the symbols should be part of the app binary. I suspect the dSYM does not match. Download a single crash report and invoke it via `symbolicatecrash -v downloadedfile.crash`

This will give lots of output, search for the part where it is looking for a matching dSYM for your app. I guess it won't find it. This usually means the .dSYM has not been created correctly by Xcode. Make sure the do a clean build first.

**Comment by rileytestut** [comment]
Sure enough, this is what I get:

Searching in Spotlight for dsym with UUID of /var/mobile/Applications/EC647A5A-6D3E-4B10-95CA-AF782175B041/[MyApp].app/[MyApp]
Running mdfind "com_apple_xcode_dsym_uuids == BBB0BABB-7254-3DFF-9236-6350377B0FE9"

## Warning: Can't find any unstripped binary that matches version of /var/mobile/Applications/EC647A5A-6D3E-4B10-95CA-AF782175B041/[MyApp].app/[MyApp]

But I don't know how to fix this, as I clean my project before archiving it, and as well as keeping the .dysm file in the archive I also move it and the .app file to the same directory as the symbolicatecrash. 

Just like in this thread https://github.com/TheRealKerni/QuincyKit/issues/43, clicking "More Info" on the dYSM file only shows "--", and not a GUID. In addition, I tried changing my project settings to what you posted, but now it won't symbolicate the system methods either. 

I'm stumped.

**Comment by fblumenberg** [comment]
Hi, I face the same problem. The only change I made was using Xcode 4.1 with Lion. Mybe there is a change here.

**Comment by DerAndereAndi** [comment]
If the dSYM doesn't show a UUID, then Xcode failed creating it. I only saw this happening once, but I don't know why this happens.

The second thing sometimes happens, as I mentioned above, that Xcode fails to update the dSYM, so it has an UUID of an earlier build.

If cleaning it doesn't help, maybe re-installing Xcode helps. Make sure to installed the Xcode 4.2 beta after (!!) the 4.1 release.

**Comment by fblumenberg** [comment]
Ok, I did a test. I created a new project in Xcode 4.1 and made a build for Archive. The resulting dSYM has no UUID in the metadata. I tried  both 4.1 and 4.2, same result.

**Comment by fblumenberg** [comment]
I think this is a problem wiht Lion. If you copy the dSYM to another folder, the metadata with the UUID is no longer there.

**Comment by DerAndereAndi** [comment]
Working fine on Lion over here. I don't get what you mean with `copy the dSYM to another folder, the metadata with the UUID is no longer there`.

You can check the dSYM on the terminal by invoking `dwarfdump --uuid your.app.dSYM`. If this doesn't give you the UUID, then try reinstalling Xcode. 4.1 first, check if it works. Then 4.2 and check again.

**Comment by rileytestut** [comment]
By using the Terminal command, it does show that my dSYM file has a UUID. This UUID also matches my App and my crash file. So why can mdfind not find it?

**Comment by fblumenberg** [comment]
**symbolicatecrash** is using mdfind to get the path for the dSYM and these metadata is missing and the script won't find a path.

**Comment by rileytestut** [comment]
But the metadata IS there, as the terminal command showed it, and matched it to my app and crash log. There should be no reason it cannot be found.

**Comment by DerAndereAndi** [comment]
Yep, that is how symbolication works. All dSYMs and binaries have to be indexed by spotlight. Apples script does it this way, and the modified version too. So make sure the path is indexed and not excluded by Spotlight (settings app). You can manually force the index by running `mdimport .` in the directory the dSYM and app is located.

Note: usually Xcode 4 puts them together into an .xcarchive package.

**Comment by rileytestut** [comment]
That looks like it has been the issue all along! I'm wondering why the folders I kept them in weren't already indexed, but oh well. To make sure though, I'm going to create a new archive build and report back with how it works.

**Comment by rileytestut** [comment]
Yup, I've tested it now twice, and using Xcode 4.2 as well so there are no problems with that. The only think I have to do is manually index the .xcarchive package each time I archive, but I'll probably just write a script to do that. Thank you very much for all your help! :)

**Comment by ribeto** [comment]
I was having some issues symbolicating.  When runing 

<pre>symbolicatecrash</pre>


The following printed

<pre>Error: No developer directory found at /Developer. Run /usr/bin/xcode-select to update the developer directory path.</pre>


I had to change the Xcode folder since it now lives in Applications by running

<pre>sudo /usr/bin/xcode-select -switch /Applications/Xcode.app/</pre>

**Comment by DerAndereAndi** [comment]
The symbolication script wasn't updated with the latest changes made by Apple, which means also looking inside the Xcode.app package now. Please try the updated script from the develop branch I just pushed.

https://github.com/TheRealKerni/QuincyKit/commit/3c4a0b163ac71599a7795508fe6a91c1ced9daa6

**Comment by ribeto** [comment]
Andreas,
Just tried the new symbolicatecrash.pl, works great!  Thanks for the fix

**Comment by sandeepgs1984** [comment]
Hi Kerni,

Can you please tell me steps how to run symbolicatecrash.pl script?

**Comment by DerAndereAndi** [comment]
@sourcebits-sandeep: call `symbolicatecrash -h` to get the list of options and how to invoke it.

**Comment by victorengel** [comment]
For someone who has never installed a perl script on a Mac before, can you give more detail than that? Last time I dealt with perl was on a remote unix host for cgi. Do I just place it somewhere (where?) and chmod it?

**Comment by yenngoc** [comment]
Hi kerni ,
Can you help me, put  file .app and .sdym onto directory Mac ?  Symbolication system method , but app not symbolicate
