### ISSUE TITLE
Alternate strings file are invalid

### ISSUE THREAD

**Issue by triplef** [bitstadium/QuincyKit#54]
Some of the QuincyAlternate.strings files are in Mac Roman encoding instead of UTF-16 and cannot be parsed (you can use "plutil -lint QuincyAlternate.strings" on the command line to test this).

Specifically this affects the de, en, nl, pt, and pt-PT localizations.

**Comment by DerAndereAndi** [comment]
Thanks Frederik for pointing this out. Just fixed it and uploaded it into the develop branch.
