### ISSUE TITLE
Demo project doesn't seem to work on iOS 4.3.2

### ISSUE THREAD

**Issue by f1fe** [bitstadium/QuincyKit#55]
I pulled the QuincyKit project and ran the QuincyDemo on iOS 4.3.2. I launch the app and select "Trigger Crash;" the app crashes. The next time that I run the app, nothing happens. No dialog, etc.

I must be missing something....?

**Comment by ashtom** [comment]
Have you tried it on the simulator or on the device? If on the device, did you start the app without the debugger? The debugger installs a signal handler which catches the crash before the app actually crashes.

**Comment by f1fe** [comment]
I'm running QuincyDemo (from https://github.com/TheRealKerni/QuincyKit/tree/develop/demo/iOS) on a device. I did start the app without the debugger. It crashes, but nothing else happens. I tried both a Debug build and a Release build.

I do see the following log lines in the Console. Is this a bug in PLCrashReport?

Sep 22 10:50:16 s052mpos05 UIKitApplication:de.buzzworks.QuincyDemo[0xe305][3304] <Notice>: [PLCrashReport] Terminated stack walking early: Corrupted frame

Sep 22 10:50:16 s052mpos05 UIKitApplication:de.buzzworks.QuincyDemo[0xe305][3304] <Notice>: [PLCrashReport] Terminated stack walking early: Corrupted frame

Sep 22 10:50:16 s052mpos05 UIKitApplication:de.buzzworks.QuincyDemo[0xe305][3304] <Notice>: [PLCrashReport] Warning -- unhandled signal sicode (signo=5, code=0). This is a bug.

Sep 22 10:50:16 s052mpos05 UIKitApplication:de.buzzworks.QuincyDemo[0xe305][3304] <Notice>: [PLCrashReport] Warning -- unhandled signal sicode (signo=5, code=0). This is a bug.

**Comment by DerAndereAndi** [comment]
Could you please set a breakpoint in line 225 method `startManager` in `BWQuincyManager.m` when starting the app again with Xcode after it crashed running without Xcode and let us know where it fails to proceed to the alert view?

**Comment by f1fe** [comment]
startManager never gets called. I checked and this code is executed: [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(startManager) name:BWQuincyNetworkBecomeReachable object:nil];

I'm running the QuincyDemo on an iPod Touch not an iPhone. Wonder if that is the difference. What triggers the name:BWQuincyNetworkBecomeReachable notification?

**Comment by DerAndereAndi** [comment]
Ok, in `QuincyDemoAppDelegate.m` did you set a submission URL for your own QuincyKit server or an `appIdentifier` for a HockeyApp app? Only those will trigger the `startManager` to run, since you need a target to send the crash report to.

`BWQuincyNetworkBecomeReachable` is optional and can be triggered in your own code if you integrate a reachability class to detect when the device comes back online, so crash reports could be send automatically, instead of hoping the device is online when the user chooses Send in the alert.

**Comment by f1fe** [comment]
That was it. I didn't set a submission URL. I missed that it was required. My fault.

Thanks for the help.
