### ISSUE TITLE
No Crashlogs on Server

### ISSUE THREAD

**Issue by naichalt** [bitstadium/QuincyKit#56]
I've set up all as in the wiki descibed, but on the server is no crashlog also in the database no crashlogs.

but in hockeyapp they appear, but ive set the server adress to mine not hockeyapps.

**Comment by DerAndereAndi** [comment]
You probably did not remove the API key from HockeyApp, which will overwrite the URL.

**Comment by naichalt** [comment]
Hey,

i removed 

#if defined (CONFIGURATION_AdHoc_Distribution)
    [[BWHockeyManager sharedHockeyManager] setAppIdentifier:@"43f0ca74be551aa120881d7433dc76d2"];
#endif

and 

[[BWQuincyManager sharedQuincyManager] setAppIdentifier:@"43f0ca74be551aa120881d7433dc76d2"];

still no logs in Database :(

**Comment by DerAndereAndi** [comment]
I suggest debugging the connection, most likely there is something not properly setup on the server. Like bundle identifier not added, so the server not accepting it. Or wrong URL etc.

**Comment by naichalt** [comment]
so i checked the connection and the identifier still no result. i get no response on the admin site or database

**Comment by DerAndereAndi** [comment]
Since I don't know your setup and what you actually did (saying you followed the wiki isn't enough), I can't help. Debug the connection and the response values etc. Make sure you added the app on the server interface by providing the bundle identifier. If you provide exact statements on which results you get where, there is a chance to help.

**Comment by naichalt** [comment]
May the Problem be that in the Crashlogs the Identifier is not the Bundle Identifier but the Name of the App?

**Comment by DerAndereAndi** [comment]
Sorry, I can only repeat myself: Without proper detailed information on what is happening where, nobody can help you.

**Comment by naichalt** [comment]
I imported the quincykit files in my project, then in the AppDelegate :

#import "BWQuincyManager.h"

and in the didFinishLaunching :

[[BWQuincyManager sharedQuincyManager] setSubmissionURL:@"http://crashreporter.MYDOMAIN.de/crash_v200.php"];

checked the path in browser and got the response "-3"

[[BWQuincyManager sharedQuincyManager] setDelegate:self];

included the crashreporter.framework
systemConfiguration.framework
UIKit.framework

then copied the serverfiles on the server 
set the DB-Connection
then i set up the database with the SQL File

Then i've set the App with the Bundle identifier on crashreporter.MYDOMAIN.de/admin

then crashed the app on Simulator and iPhone
restartet the App and clicked on send Report.

checked on the site in Browser = No Reports

**Comment by DerAndereAndi** [comment]
I'll try it again with some detailed questions, as I asked you to debug what the server is returning:
- Set a breakpoint here: https://github.com/TheRealKerni/QuincyKit/blob/develop/client/iOS/BWQuincyManager.m#L850
- Add these lines below
  NSString *responseString = [[[NSString alloc] initWithBytes:[_responseData bytes] length:[_responseData length] encoding: NSUTF8StringEncoding] autorelease];
  NSLog(@"Received API response: %@", responseString);
- Give us the value of `_statusCode`
- Give us the value of `responseString` 

Anyway, why are you trying to use your own server instead of using HockeyApp?

**Comment by naichalt** [comment]
I love the Workflow of Hockeyapp and use it for other projects but on these my Boss wants to have the Company Branding on the Pages so i've to set up a Structure of HockeyKit Server and QuincyKit server :)

so this is what i get as Response 

2011-09-29 11:18:46.897 NAME OF THE APP[12619:207] Received API response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/css; charset=utf-8" />
        <title>Fehler 500</title>
        <link rel="stylesheet" type="text/css" href="/mittwald_system_pages/css/style.css">  
        
    </head>
    <body>
        <div id="box">
            <div id="oben"></div>
            <div id="textbox">
                <div id="textboxcontent">
                    <span class="rad">&nbsp;</span>  
                    <h1>Fehler 500</h1>  
                    <p>Interner Server Fehler 500</p>
                </div>
            </div>
        <div id="unten"></div>
        </div>
    </body>
</html>

thats really strange !!

**Comment by DerAndereAndi** [comment]
Try running the `test_setup.php` script on the server, which is in the same directory as `crash_v200.php`

**Comment by naichalt** [comment]
XMLReader: passed
Prowl: passed
Boxcar: passed
Database access: passed

**Comment by DerAndereAndi** [comment]
Well, you need to dig into your servers logs and find out yourself by trying and adding more logging etc. Can't help you there. Sorry.
