### ISSUE TITLE
Warning: Could not open fork matching current architecture for OSO archive / Could not open OSO file

### ISSUE THREAD

**Issue by triplef** [bitstadium/QuincyKit#59]
Launching our app in the debugger with Xcode we’re seeing the following warnings from GDB:

> warning: Could not open fork matching current architecture for OSO archive "OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter"
> warning: Could not open OSO file OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter(CrashReporter.o) to scan for pubtypes for objfile /build/Debug/OurApp.app/OurApp
> warning: Could not open fork matching current architecture for OSO archive "OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter"
> warning: Could not open OSO file OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter(PLCrashSignalHandler.o) to scan for pubtypes for objfile /build/Debug/OurApp.app/OurApp
> warning: Could not open fork matching current architecture for OSO archive "OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter"
> warning: Could not open OSO file OurApp/Frameworks/iOS/CrashReporter.framework/CrashReporter(PLCrashFrameWalker.o) to scan for pubtypes for objfile /build/Debug/OurApp.app/OurApp
> ... _(repeated seemingly for every class of CrashReporter.framework)_

They don’t seem to affect anything, but has anyone else seen these or know what this is about?

This is using Xcode 4.2 GM, but we’ve seen these with previous versions too.

Thanks!

**Comment by DerAndereAndi** [comment]
Never saw that, and never heard that again. Closing this ticket for now.
