### ISSUE TITLE
Separate different exceptions into different groups

### ISSUE THREAD

**Issue by pocketpixels** [bitstadium/QuincyKit#61]
Currently it seems that all exceptions are reported under a single crash group. 
I think it would be preferable to have a separate crash group for each type of exception (based on the exception message).

**Comment by pocketpixels** [comment]
A separate but related question: Is it possible to get a stack trace showing where the exception happened? 
The stack traces I am currently getting for exceptions all look like this, which is not too helpful: 

Thread 0 Crashed:
0   libsystem_kernel.dylib              0x00010848 __kill + 8
1   CoreFoundation                      0x000b9987 __handleUncaughtException + 75
2   libobjc.A.dylib                     0x000092d1 _objc_terminate + 129
3   libc++abi.dylib                     0x000043c5 _ZL19safe_handler_callerPFvvE + 77
4   libc++abi.dylib                     0x00004451 operator delete(void*) + 1
5   libc++abi.dylib                     0x00005825 __cxa_current_exception_type + 1
6   libobjc.A.dylib                     0x00009235 objc_exception_rethrow + 13
7   CoreFoundation                      0x0000f545 CFRunLoopRunSpecific + 405
8   CoreFoundation                      0x0000f3a5 CFRunLoopRunInMode + 105
9   GraphicsServices                    0x00003fed GSEventRunModal + 157
10  UIKit                               0x00031743 UIApplicationMain + 1091
11  APPNAME                         0x00003ed7 main (main.m:14)

**Comment by DerAndereAndi** [comment]
Hi,

we are doing this, grouping of crashes by line number and exception, at HockeyApp.net, but this is a little more advanced and requires quite some more data to be collected and processed, also in the database. I started a feature/21 branch with some enhancements, e.g. if symbolication happened, adding that to the crash group description. You are more than welcome to join working on it and help improving it.

Regarding the second point, there is a new version of PLCrashreporter being worked on, that will provide the backtrace for exceptions too. But it is not finished yet and needs to get some more changes regarding the formatting of the crash reports and more intensive testing.
- Andreas

**Comment by pocketpixels** [comment]
Thanks for the quick reply. That sounds very promising. I am looking forward to that future PLCrashreporter version.

I looked at the feature/21 branch before. The "request more info" feature in it is very interesting to me. 
Do you keep that branch in a state that should be reasonably safe to deploy at any point or is it likely to contain unfinished work-in-progress changes? 
If I was to switch from the develop branch to the code from that feature branch, could I keep using the same database or would I need to start with a fresh one? 
Thank you, 
Hendrik

**Comment by DerAndereAndi** [comment]
This has all ben implemented and available for a while. Closing the ticket.
