### ISSUE TITLE
Can I force saving crash info without actual crash on iOS?

### ISSUE THREAD

**Issue by jamusj** [bitstadium/QuincyKit#62]
In my app, I have certain error scenarios that I can detect, but can't recover from (mostly core data save failures).

For now, I can abort() to save the crash info at the point of failure, but this isn't very user friendly.  I would like to save the backtrace info at the point of failure, then exit gracefully by displaying a modal dialog that a crash occurred and to press home to exit.  Either after the next time the user starts the app, or before the user presses home, I'd like QuincyKit to send the backtrace.

Is there any way to save the crash info without actually crashing?

**Comment by DerAndereAndi** [comment]
Hi,

neither QuincyKit nor PLCrashReporter are designed for that. You better go by writing your own code to do something like that. Starting iOS4 you can get the backtrace of the main thread which should be what you need.
