### ISSUE TITLE
Allow user enter feedback when sending a report

### ISSUE THREAD

**Issue by jfradj** [bitstadium/QuincyKit#64]
A cool option will be to allow the user explain briefly what he does to crash the app.
I don't know what the lib should do if the user tell it to automatically send reports...

BTW thanks for a such great library!

**Comment by DerAndereAndi** [comment]
There is some work currently being done on that in the feature/21 branch with a lot of contribution from foozmeat. But problems like the one you mentioned are not yet solved and it currently sends out an email, while I'd like to have the text being integrated into the crash report description instead.
