### ISSUE TITLE
feedback on jailbroken devices

### ISSUE THREAD

**Issue by foozmeat** [bitstadium/QuincyKit#66]
We sometimes see crashes that only occur on jailbroken devices. In general we're not going to address these and I'd like to provide feedback to the user so they don't email us about it. This would require simply another status coda and some new strings. I'll probably add this on a feature branch in my fork. I'm just filing this here to give you a heads up.

James

**Comment by DerAndereAndi** [comment]
Hi James, thanks, sounds good.
