### ISSUE TITLE
Mac crash report window layout issue

### ISSUE THREAD

**Issue by triplef** [bitstadium/QuincyKit#71]
When clicking "Show Details" in the problem report window and then closing the comments section by clicking the disclosure triangle, the window layout will get messed up (the problem details fields won’t move up to fill the space opened up by the hidden comments field).

**Comment by DerAndereAndi** [comment]
Is this reproducible with the demo app? I can't reproduce it so far.

**Comment by triplef** [comment]
Yes:
1. Click "Show Details"
2. Click the disclosure triangle next to "Comments"

Here is a screenshot: http://dl.dropbox.com/u/536254/QuincyKitUIIssue.png

**Comment by DerAndereAndi** [comment]
Thanks, found it and fixed it. Check the develop branch. There is also a brand new implementation in the feature/newMac branch, with an improved client. That one still relies on the original Mac OS X crash report files, but it supports feedback, queueing if sending failed and better detects old crash reports which should not be presented. Would be great if you could help testing that one, it is working fine for us so far.

**Comment by triplef** [comment]
Perfect, thanks. We’ll check it out.
