### ISSUE TITLE
Signing QuincyKit for Mac App Store

### ISSUE THREAD

**Issue by triplef** [bitstadium/QuincyKit#72]
We got the following "warning" when submitting our app using QuincyKit to the Mac App Store:

> We have discovered one or more issues with your recent binary submission for "MyApp". Your app has proceeded to review, but the following issues should be corrected in your next submission:
> 
> **Invalid Signature** - the nested app bundle (MyApp.app/Contents/Frameworks/Quincy.framework) is not signed, the signature is invalid, or it is not signed with an Apple submission certificate. Refer to the Code Signing and Application Sandboxing Guide for more information.

I was wondering if it would be easiest to just add the QuincyKit files directly to the main app instead of using it as a framework, so one doesn’t have to worry about signing the framework additionally. Is there anything that would stand in the way against that (e.g. code- or license-wise)?

**Comment by DerAndereAndi** [comment]
Hi Frederik,
1. QuincyKit on Mac only works with sandboxing, if you include the crash reporter path to your entitlements, i.e. setting com.apple.security.temporary-exception.files.absolute-path.read-only to the crash log directory
2. You can include the source files easily into your app. The demo app shows which ones to use.

Best,
Andreas

**Comment by triplef** [comment]
Great, thanks!
