### ISSUE TITLE
Demo app: user dialog box not appearing on crash, but on re-start of app

### ISSUE THREAD

**Issue by mts749** [bitstadium/QuincyKit#74]
I have successfully set up QuicyKit and am testing it with QuincyDemo (compiled against 5.0 SDK). I can send, retrieve and symbolicate crash logs from my external server. All this works as expected ... sort of.

When I run QuincyDemo the following anomalous behaviour is observed:
- Device (iPhone4s iOS5.0, debugger off - untethered). The framework does reliably catch crashes and generate logs, but the user dialog box is not presented to the user. The app appears to quit, but is actually put into the background - at least it appears that way. Then when the demo app is restarted (becomes active) the dialog box appears after a slight delay. If the user selects  Send Report, a crash log from the previous crash is sent.
- Simulator (5.0 and 4.3): the framework does not appear to reliably catch all crashes. At first it did exhibit the same behaviour as described above on the device. But at some point in testing I was unable to get it to do so at all. 

Hmm, after writing all this up, I wonder if the above behaviour has something to do with the fact that I compiling against 5.0 SDK?

Any advice would be much appreciated.

Thanks,
Martin

**Comment by DerAndereAndi** [comment]
Hi,

if you test it in the simulator, make sure Xcode debugger is not attached to the process. Also, the purpose is mainly to catch crashes on the device, and not in the simulator. Since you easily can find those crashes in the Xcode organizer. If it is not reliably catching crashes on the simulator, you may want to create a ticket in the PLCrashReporter page: http://code.google.com/p/plcrashreporter/issues/list

Best,
Andreas

**Comment by mts749** [comment]
Ok, thanks, will do. 

But is there something I can do about the behavior I am seeing on the device?

Cheers,
Martin

**Comment by DerAndereAndi** [comment]
That is the way it is supposed to work. The dialog appears after the next start. It is dangerous trying to do anything right when the crash happened. It will always be shown on the next start and send afterwards.

**Comment by mts749** [comment]
Ahh, thanks for clearing that up! 

And many thanks for the library!
