### ISSUE TITLE
Seeking advice: Works with QuincyDemo, can't get to work in my app

### ISSUE THREAD

**Issue by mts749** [bitstadium/QuincyKit#75]
QuincyKit works perfectly as advertised using QuincyDemo (on the device). When I follow the same pattern in my own code, it does not generate a crash log. When I run the app while the device is tethered I can see that QuincyKit is initialized (I have inserted NSLog() statements) and that a stack trace is produced, but no log is generated. This differs from QuicnyDemo where I see the following in the console:

> Dec  3 07:47:13 unknown ReportCrash[1902] <Notice>: Formulating crash report for process QuincyDemo[1239]
> Dec  3 07:47:13 unknown com.apple.launchd[1] <Warning>: (UIKitApplication:de.buzzworks.QuincyDemo[0xceda]) Job appears to have crashed: Trace/BPT trap: 5
> Dec  3 07:47:13 unknown SpringBoard[15] <Warning>: Application 'QuincyDemo' exited abnormally with signal 5: Trace/BPT trap: 5
> Dec  3 07:47:14 unknown ReportCrash[1902] <Error>: Saved crashreport to /var/mobile/Library/Logs/CrashReporter/QuincyDemo_2011-12-03-074713_Phone.plist using uid: 0 gid: 0, synthetic_euid: 501 egid: 0

This is what appears under my app:

> Dec  3 07:50:04 unknown Am[1906] <Warning>: Uncaught exception: **\* -[__NSArrayI objectAtIndex:]: index 23 beyond bounds for empty array
> Dec  3 07:50:04 unknown Am[1906] <Warning>: Stack trace: (
>         0   CoreFoundation                      0x371078d7 __exceptionPreprocess + 186
>         1   libobjc.A.dylib                     0x324771e5 objc_exception_throw + 32
>         2   CoreFoundation                      0x3705f275 -[__NSArrayI objectAtIndex:] + 164
>         3   Am                        0x00048ba1 -[RootViewController debug2:] + 44
>                 ...

So it clearly is not catching the exception. 

I realize that this may not be strictly a QuincyKit issue (may be a plcrashreporter problem, but any advice on how to proceed with debugging this would be very much appreciated.

Martin

**Comment by DerAndereAndi** [comment]
Are you setting up a server address or HockeyApp appIdentifier? The code will not setup PLCrashReporter if it has no target for sending the reports to.

**Comment by mts749** [comment]
Thanks for the quick response.

I am using my own server and am using the same address for the QuincyDemo and for my app.

**Comment by DerAndereAndi** [comment]
So if you are initializing the client with your server URL and NOT running while Xcode debugger is attached, it should work.

**Comment by mts749** [comment]
Yes, I am not running with the debugger attached and initializing with my server and yet it is not working (as I think the logs above show). 

Is there anything else I can do to further debug this?

**Comment by DerAndereAndi** [comment]
The logs above do not show me what your are logging or what is going on. Neither was it clear to me what you are doing, like testing with debugger on or off. Hence my questions.

My assumption is: PLCrashReporter is not being initialized in your app.

To find out, you should set some breakpoints when running the app the first time:
line 177: `if (![crashReporter enableCrashReporterAndReturnError: &error])`

Is that working?

Next after the app is crashed, run it again with the debugger attached. And set a breakpoint in line 727 `handleCrashReport` function. What is going on in there?

**Comment by mts749** [comment]
(It sounds like I may have came across as somewhat snarky. I certainly did not mean to convey that and if so, I apologize).

Thanks again for the quick response. 

Here's what I found out:

> To find out, you should set some breakpoints when running the app the first time:
> line 177: if (![crashReporter enableCrashReporterAndReturnError: &error])

It successfully executes the above line. (the condition fails).

> Next after the app is crashed, run it again with the debugger attached. And set a breakpoint in line 727 handleCrashReport function. What is going on in there?

It never executes `handleCrashReport`. 

I investigated a bit further and can tell you that `startManager` is being called but the initial condition `if (!_sendingInProgress && [self hasPendingCrashReport])` fails and therefore the method just returns. `hasPendingCrashReport` is called and since  `_crashReportActiviated` is `YES`, the body of the if statement is executed, but  `hasPendingCrashReport` returns `NO` because `_crashesDir` is empty.

Does any of this help?

**Comment by DerAndereAndi** [comment]
Ok, so the crash is really not catched. Are you sure there is no duplicate or older version of the PLCrashreporter framework anywhere in the project? Or any other framework trying to catch the crash and so not making it available?

How do you test the crash, could you post your code? Have you tried that code with the demo app?

**Comment by mts749** [comment]
I have to go now so I will have to investigate your questions later tonight or tomorrow morning (EST). But 1 question: by
>How do you test the crash

do you mean what code do I use to trigger the crash? 

Or something else?

**Comment by DerAndereAndi** [comment]
Yes, how do you trigger the crash. Just want to make sure we think of all possibilities and find the cause.

**Comment by mts749** [comment]
Well ... this is a bit embarrassing .... 

I can't believe that I missed it before: yes, indeed elsewhere in my code I was trapping exceptions. There is a bug in Xcode 4.2 which prevents Xcode from automatically showing a backtrace on an exception. So I had added code to trap exceptions and show a backtrace on the console. Unfortunately, I had forgotten about it. 

(By the way a better way of accomplishing the same thing is to set a breakpoint for all exceptions. This has the advantage of not trapping exceptions when breakpoints are not enabled).

Sorry for causing needless work on my behalf and thanks again for your efforts and, of course, for the library.

Martin

**Comment by DerAndereAndi** [comment]
Glad you found it :)
