### ISSUE TITLE
crash_v200.php bitwise operator issue for $crash["applicationname"]

### ISSUE THREAD

**Issue by waggyza** [bitstadium/QuincyKit#76]
Not sure if this was intentional but line 406 of crash_v200.php has an if statement that uses 
& $crash["applicationname"] instead of
&& $crash["applicationname"]

**Comment by DerAndereAndi** [comment]
Thanks for the hint, just pushed a fix to the develop branch

**Comment by waggyza** [comment]
Pleasure,

While I have you on email one quick question. Everything seems to be working great except when I set a fix version and description, I still get a CrashReportStatusUnknown on my iOS app.
That's why I was looking through the php trying to find where the status is sent back.

Regards,

Dan

**Comment by DerAndereAndi** [comment]
Does the fix version exist? Does it have a status?

**Comment by waggyza** [comment]
Ok, you've pointed me to my issue.  I didn't see the new version which was obviously added automatically, and now that I see it, I changed it to In development, and the notification came through.

Many thanks for the response and help.

Regards,

Dan
