### ISSUE TITLE
Doesn't Symbolicate SYSTEM methods, only app methods.

### ISSUE THREAD

**Issue by rileytestut** [bitstadium/QuincyKit#78]
In what seems to be a complete opposite problem of what most people (myself included) have: my crash reports are semi-symbolicated, but they only symbolicate my app methods and not any framework methods (such as UIKit, CoreGraphics, etc.)

I figured the problem would be that I have an outdated symbolicatecrash file, so I downloaded the symbolicatecrash.pl file. However, no matter what I type into terminal (including "chmod -x symbolicatecrash.pl"), the perl file never is turned into an executable. 

Is this the root of the problem? If so, how can I turn the perl file into an executable? And if it's not the problem, any idea what it is?

**Comment by DerAndereAndi** [comment]
The command is `chmod +x symbolicatecrash.pl`. You are removing the executable flag with `-x`.

But since your app symbols are shown, I guess including line numbers, the problem seems to be a different one, since the crash reports only get that information by running the perl script. Please check if you have the system symbols for the iOS versions of the crash reports, that have missing system symbols. Check the iOS version reported in the crash report, and then check your system directory `/Developer/Platforms/iPhoneOS.platform/DeviceSupport` if it has a subfolder for that iOS version.

**Comment by rileytestut** [comment]
Ah that was just a typo in my question, I've done it again with +x and still nothing happens. Would there be a problem in continuing to use the symbolicatecrash from a few months ago?

Besides that, the crash report is from 5.0.1, and it seems there is no 5.0.1 folder in that directory, just 5.0.

**Comment by DerAndereAndi** [comment]
The second part is the key problem, the script is not the problem. You don't have the symbols where it could resolve the addresses into the classes and method names. You need a device having 5.0.1 installed and connect it to your computer with Xcode running, so it can fetch the symbols.

**Comment by rileytestut** [comment]
For some reason it doesn't ask me to fetch debug symbols as it usually does. I even just updated my iPad to 5.0.1 from 5.0 and still nothing. Any way to force a fetch?

**Comment by DerAndereAndi** [comment]
Well, then Xcode has the data already lying around somewhere else. They play a little game by placing the symbols in another place for every release during the last months, and also hardly update their script which rely on them.

So check `~/Library/Developer/Xcode/iOS DeviceSupport/` and if you find it in there, copy it to the other symbols directory I mentioned previously.

P.S.: You may want to take a look at HockeyApp.net, a hosted solution for QuincyKit & HockeyKit and much more, which does the symbolication for you and has much better crash grouping. I am also one of its developers.

**Comment by rileytestut** [comment]
I get these errors now when symbolicating:    

```
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/Foundation.framework/Foundation truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 22 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/Foundation.framework/Foundation
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 17 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/UIKit.framework/UIKit truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 41 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/UIKit.framework/UIKit
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/PrivateFrameworks/MediaToolbox.framework/MediaToolbox truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 41 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/PrivateFrameworks/MediaToolbox.framework/MediaToolbox
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/System/Library/Frameworks/CoreMedia.framework/CoreMedia truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 22 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/System/Library/Frameworks/CoreMedia.framework/CoreMedia
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/PrivateFrameworks/WebCore.framework/WebCore truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 28 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/PrivateFrameworks/WebCore.framework/WebCore
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/libobjc.A.dylib truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 12 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/libobjc.A.dylib
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/usr/lib/system/libdispatch.dylib truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 11 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/usr/lib/system/libdispatch.dylib
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/system/libsystem_c.dylib truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 11 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/system/libsystem_c.dylib
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 15 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A402)/Symbols/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
Use of uninitialized value $bundle in string eq at /Users/Riley/Documents/XCode/Beta Test Crashes/symbolicatecrash line 784.
size: for architecture armv7 object: /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/system/libsystem_kernel.dylib truncated or malformed object (dataoff field of LC_FUNCTION_STARTS command 10 extends past the end of the file)
Error in symbol file for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/5.0.1 (9A404)/Symbols/usr/lib/system/libsystem_kernel.dylib
```

**Comment by DerAndereAndi** [comment]
This means that you did grab the symbols previously and Xcode placed it in that directory, but you did not use the latest public Xcode release to do that. So delete both 5.0.1 directories, and grab them again and make sure using the latest public (NOT the beta) Xcode version to do that.

**Comment by rileytestut** [comment]
After searching the developer forums, it appears this is a known issue with Xcode 4.2:

https://devforums.apple.com/message/578722

Xcode 4.2 continuously imports corrupted debug symbols from 5.0.1. I was wary of updating Xcode 4.2 to 4.2.1 as there have been a few submitting to App Store bugs, but it seems this may be the only solution. Hopefully Xcode 4.2.1 will fix this issue.

**Comment by DerAndereAndi** [comment]
You always have to use a new Xcode version to grab the symbols, that ships about the time the new iOS version is shipped. In case of 5.0.1 the Xcode version was shipped a few days later. Otherwise, the symbols will not be usable, as it is in your case.

**Comment by rileytestut** [comment]
This seems to be the issue, however, the crash reports don't seem as helpful as they did before all these changes. I'll keep testing and maybe it's just the way Apple structures them now.

**Comment by DerAndereAndi** [comment]
The structure did not change. I have no idea what you are referring to. We do symbolicate a massive amount of crash reports daily at HockeyApp without issues, so you might want to try that out or give more specifics so I can help.
