### ISSUE TITLE
Crash in BWQuincyManager

### ISSUE THREAD

**Issue by JoeSzymanski** [bitstadium/QuincyKit#79]
Our app has a reported crash occurring in BWQuincyManager.  It appears that some of the required data doesn't exist in the response from the server, so we get an exception trying to build a string.

The code that is causing the crash is below:

NSMutableDictionary _response = [NSPropertyListSerialization propertyListFromData:_responseData
                                                                             mutabilityOption:NSPropertyListMutableContainersAndLeaves
                                                                                       format:nil
                                                                             errorDescription:NULL];
_serverResult = (CrashReportStatus)[[response objectForKey:@"status"] intValue];
_feedbackRequestID = [[NSString alloc] initWithString:[response objectForKey:@"id"]];  // *_ This is the method that crashes **
_feedbackDelayInterval = [[response objectForKey:@"delay"] floatValue];

A crash report can be provided, if necessary.

**Comment by DerAndereAndi** [comment]
Please update your QuincyKit code to the latest version, this has been fixed here: https://github.com/TheRealKerni/QuincyKit/commit/338a4cb9f8e4edd69409f6769feffe937140f317

The crash happened if the user was e.g. in a hotel and did not yet log into the hotel portal. So the crash happened and was queued to be send the next time.
