### ISSUE TITLE
QuincyKit requires MoreUtils.pm which is not installed on Lion

### ISSUE THREAD

**Issue by buscarini** [bitstadium/QuincyKit#81]
I have set up QuincyKit correctly on my machine, but I can't make symbolicate.php work. The symbolication script works fine with the readme instructions, but if I add the -o option it crashes saying something like this:

Can't locate List/MoreUtils.pm in @INC

I think this module isn't installed on Mac OS X Lion by default, and that's why it's failing.

**Comment by DerAndereAndi** [comment]
Is Xcode installed? Make sure it is and also that the device symbols for the various iOS version are available, otherwise those cannot be symbolicated.

**Comment by buscarini** [comment]
Xcode is installed and the required iOS version is available. The symbolication is working, that is not the problem. The problem is the -o option of the script, which is used by symbolicate.php. That option requires an unavailable perl module.

**Comment by DerAndereAndi** [comment]
If you look into `/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/DTDeviceKit.framework/Versions/A/Resources/symbolicatecrash` the original symbolication script from Apple, you'll see that the module is also referenced in there. I did not add it, so I assumed if it is not part of Lion it could have been part of Xcode. I did never ever on any of my Macs had to do anything special to get this module.

Maybe during the installation of Xcode the unix tools where not added, as far as I remember this is a checkbox in the installer that you can set or remove. I don't know where perl stores its modules and couldn't find it quickly either.

**Comment by buscarini** [comment]
Thanks, that makes sense. I remember that checkbox from the old installer, but I'm not sure it's in the new one. I'll try that and see if it works.

**Comment by buscarini** [comment]
I finally managed to solve this, but I had to install that perl module by myself. I put the instructions here in case anyone else has the same problem:
- sudo perl -MCPAN -e shell
- Press return for every question to use the default values
- install List::MoreUtils

After a while it said:
make install  -- OK

And now the symbolicate.php script works fine.

**Comment by lukaszmargielewski** [comment]
@buscarini: thank you very much for this hint. It solved my problem also.

**Comment by kusinawi** [comment]
@buscarini: wonderfull, also works for me. thx!
