### ISSUE TITLE
QuincyDemo not working

### ISSUE THREAD

**Issue by basvankuijck** [bitstadium/QuincyKit#82]
I've downloaded the demo and opened it in Xcode4 and tried running it on the Simulator (iOS 5.0) and my iPhone (iOS5).
Both "devices" won't catch the (exception) crash. They just crash 'the normal way' with a SIGABRT or a 'Null pointer argument'.

I haven't done anything to the code of the demo. Just download and (test)run.

Anything that I did wrong or should keep in mind? I'm using Xcode 4.2

**Comment by DerAndereAndi** [comment]
Did you run it with Xcode attached? You need to run the app standalone.

**Comment by basvankuijck** [comment]
Okay, didn't know that.

If I run it standalone the app still closes / crashes without showing an alertview.
However a crashreport is generated in the /Library/Cashes/crashes/ folder.

**Comment by DerAndereAndi** [comment]
The alert is shown on the next startup of the app. Doing mostly anything when it crashes is dangerous and should be avoided at all cast. Especially running Objective-C code.

**Comment by basvankuijck** [comment]
Okay, I also "forgot" to set the submissionURL, else the alertview won't be shown.

Thanks for the fast replies!
