### ISSUE TITLE
iOS Version number

### ISSUE THREAD

**Issue by bryanrahn** [bitstadium/QuincyKit#86]
I can't find anywhere to tell what version I have based on the iOS package. Can you include the version number within the iOS package?

**Comment by DerAndereAndi** [comment]
Good point. Will add it in the future.

**Comment by DerAndereAndi** [comment]
This is available, and was added first with this commit: https://github.com/TheRealKerni/QuincyKit/commit/54c23b20e85d20e2697547d3008066e36150d0f1
