### ISSUE TITLE
QuincyKit _urlConnection and String leak

### ISSUE THREAD

**Issue by bogardon** [bitstadium/QuincyKit#92]
I don't know about you guys, but whenever I send a crash report. I get two leaks.
1. `_urlConnection`, this is easily fixed by a call to release in either `didFinishLoad` or `didFail`
2. some NSString that's created in `PLCrashReport *report = [[[PLCrashReport alloc] initWithData:crashData error:&error] autorelease];` in line 496.

Could we get this fixed please? Thanks.

**Comment by DerAndereAndi** [comment]
Thanks for the hint!

Actually `_urlConnection` may not be released, and it shouldn't be set to `nil` either. So I removed that and this leak is gone. See https://github.com/TheRealKerni/QuincyKit/commit/95996f18744372b4bb03c35d94c48f205b27e2aa

The crash in PLCrashReporter has also been identified and a new version will be available soonish.

Thanks again! All the time and nobody saw those until now.
