### ISSUE TITLE
missing information in crash logs on server for iOS

### ISSUE THREAD

**Issue by ghost** [bitstadium/QuincyKit#94]
Hey,
there is some information missing in the submitted crash-logs on server.
If i look in crash.logs at database there is 'hardware model' missing (in the crash-log).
An orignal crash-log looks like :

...
Hardware Model:      iPhone3,1
Process:         Twitter [2400]
Path:            /var/mobile/Applications/1275518C-7F62-4407-A590-36AFC1C59819/Twitter.app/Twitter
Identifier:      Twitter
Version:         ??? (???)
Code Type:       ARM (Native)
Parent Process:  launchd [1]
... 

This is the un-symbolized crash-log.
Symbolication doesn't work at our setup (but that is another issue)

cheers
-r

**Comment by DerAndereAndi** [comment]
Ok, let's dive into that.
1. There is no code on the server which manipulates the Crash Report logs
2. In the current Crash Log formatter code at http://code.google.com/p/plcrashreporter/source/browse/trunk/Source/PLCrashReportTextFormatter.m#162 the Hardware Model appears after the `Incident Identifier`.
3. The crash report posted above is one I guess you got from the device which is generated by iOS, and not one generated by this SDK
4. A previous version of this SDK did not provide any Hardware Model information in the crash report at all. See this commit: https://github.com/TheRealKerni/QuincyKit/commit/6a274ea2ff3a91d454897a01ccb748a0fc595302

The conclusion of this is: you are simply using an old version of the SDK and PLCrashReporter, which does not submit the Hardware Model as part of the crash log.
