### ISSUE TITLE
How read the table of the crash

### ISSUE THREAD

**Issue by Piero87** [bitstadium/QuincyKit#97]
hello, this is a question and not a issue, i'm a newbie in web server and my sql, so my question is, if i install corret the quincy kit, how i can read from the table?...i have to write my php code right? there is some example to read what crash i have received on the database?

thanks for all the work!

**Comment by DerAndereAndi** [comment]
The repository contains all server code need in the `server/php` subdirectory. You can find documentation here in the wiki or a quick overview in the readme file in that directory.

**Comment by Piero87** [comment]
i read the installation and the setup in the wiki, but i don't undestand when the crash arrive to my server how i can read it, what file i have to open to read the crash, or i have to implement a php code?...i'm a newbie and first to start install i want understand all the steps :)

**Comment by DerAndereAndi** [comment]
Well, you integrate the SDK into your app. Then when the app crashes and starts again, the user get's a dialog asking if he wants to submit it. Then your app sends the crash report to the server and you will also see it on the server given you did setup everything correctly as documented.

**Comment by Piero87** [comment]
yes i have understand all of this step, so to read the crash i have only to read my sql database?

**Comment by DerAndereAndi** [comment]
No, the server code provides a complete web interface.

**Comment by Piero87** [comment]
really? great! :), and what is the server page i have to open to see it?

**Comment by DerAndereAndi** [comment]
That depends on where you install it. The web interface is located under `admin/`, as you can find the index.html page etc. in the corresponding source folder.

**Comment by Piero87** [comment]
thank you very much for your answer!

**Comment by Piero87** [comment]
sorry last question really, how i can do this:

Execute the SQL statements from database_schema.sql in your MySQL database on the web server

what is the command to execute it?

**Comment by DerAndereAndi** [comment]
You might want to check out various documentations on how to setup PHP and MySQL, maybe also the documentation provided by your server hosting provider. If you don't have any experience setting up such environments, you really might want to reconsider using your own setup and use a hosted solution instead.

I am not able to provide support other than checking out bugs and hopefully fixing them.

**Comment by Piero87** [comment]
ok, thank you again for the help :)
